#!/usr/bin/env python3
"""One-shot script: fill zh-TW translations for flyto-code scope."""
import json
from pathlib import Path

zh_file = Path(__file__).parent.parent / 'locales' / 'code' / 'zh-TW' / 'code.json'

with open(zh_file, encoding='utf-8') as f:
    data = json.load(f)

zh = data['translations']

T = {
    "code.autofix.confidenceLow": "低信心",
    "code.autofix.confidenceReasonFailed": "{n} 個驗證閘道回報失敗 \u2014 請參閱下方 {gate} 了解詳情。",
    "code.autofix.confidenceReasonSkipped": "驗證閘道被跳過 ({list}) \u2014 修補未經實際驗證。",
    "code.autofix.confidenceReasonTier1": "確定性轉換 ({category}) 且 {n} 個閘道通過 \u2014 機械式變更，可安全建立 PR。",
    "code.autofix.confidenceReasonTier2": "AI 產生的修補且 {n} 個閘道通過 \u2014 程式碼正確性仍需人工審查。",
    "code.autofix.disclaimerSAST": "AI 產生的修補 \u2014 程式碼正確性需要人工審查。驗證閘道僅檢查 lint 與測試是否通過，不驗證變更是否保留原始意圖。",
    "code.autofix.downloadPatch": "下載修補檔",
    "code.autofix.emptyTitle": "尚無 AutoFix 發現",
    "code.autofix.fetchError": "無法載入此發現 \u2014 引擎回傳錯誤。該發現可能已在最近一次掃描中解決，或快取不同步。重新執行掃描通常可以解決此問題。",
    "code.autofix.noMatchTitle": "沒有符合的發現",
    "code.autofix.subtitle": "AI 驅動的相依性、程式碼與基礎架構修復建議",
    "code.autofix.viewContext": "檢視發現上下文",
    "code.autofix.warroom.noRules": "尚未設定規則。執行掃描以填入。",
    "code.autofix.warroom.promotionEmptyTitle": "尚無候選項目",
    "code.common.delete": "刪除",
    "code.common.dismiss": "忽略",
    "code.common.noFavorites": "尚無收藏項目",
    "code.dashboard.actionCritical": "修復 {n} 個嚴重弱點",
    "code.dashboard.actionStalePRs": "審查 {n} 個過時的 Pull Request",
    "code.dashboard.actionUnscanned": "掃描 {n} 個未掃描的儲存庫",
    "code.dashboard.connectToStartDesc": "連接您的 GitHub 或 GitLab 儲存庫以開始監控您的組織",
    "code.dashboard.kpiCoverage": "覆蓋率",
    "code.dashboard.kpiCritical": "嚴重",
    "code.dashboard.kpiFixed": "已解決",
    "code.dashboard.kpiHigh": "高",
    "code.dashboard.noDataDesc": "您的儲存庫已連接但尚未產生掃描結果",
    "code.dashboard.riskAtRisk": "{n} 個儲存庫存在安全疑慮",
    "code.dashboard.riskClear": "您的組織目前沒有已知的安全問題",
    "code.dashboard.riskCritical": "{n} 個嚴重弱點需要立即處理",
    "code.dashboard.riskMatrix": "資產風險矩陣",
    "code.dashboard.viewCritical": "檢視嚴重項目",
    "code.dast.apiDiscovery": "API 掃描",
    "code.dast.apiDiscoveryEmpty": "執行探索以掃描 API 端點、文件與框架。",
    "code.dast.apiDocsFound": "發現 API 文件",
    "code.dast.attackSurface": "攻擊面",
    "code.dast.category": "分類",
    "code.dast.deleteConfirm": "確定要刪除「{name}」嗎？所有探索資料、子網域與掃描結果將被永久移除。",
    "code.dast.deleteDomain": "刪除網域",
    "code.dast.emptyDesc": "新增您的網域以探索暴露的服務、SSL 狀態、DNS 記錄、技術堆疊，以及外部周界的潛在弱點。",
    "code.dast.emptyTitle": "探索您的攻擊面",
    "code.dast.frameworkDetected": "偵測到框架",
    "code.dast.graphqlIntrospection": "GraphQL Introspection 已啟用",
    "code.dast.graphqlWarning": "Introspection 已啟用 \u2014 這會向任何人暴露完整的 Schema。請在正式環境中停用。",
    "code.dast.jsBundleEndpoints": "來自 JS Bundle 的端點",
    "code.dast.noApiFindings": "未偵測到 API 文件、GraphQL 或 JS Bundle 端點。",
    "code.dast.noChecksTitle": "沒有符合篩選條件的檢查",
    "code.dast.subtitle": "探索並監控所有網域的外部攻擊面",
    "code.domains.deleteProject": "刪除專案",
    "code.domains.environment": "環境",
    "code.domains.importBtn": "匯入 {n} 個網域",
    "code.domains.importCsv": "匯入 CSV",
    "code.domains.importDiscovery": "正在背景執行每個新網域的探索。",
    "code.domains.importHint": "貼上網域（每行一個）或上傳 CSV 檔案。子網域會自動歸類在其根網域下。",
    "code.domains.importSuccess": "匯入完成",
    "code.domains.importTitle": "匯入網域",
    "code.domains.linkRepo": "連結至儲存庫",
    "code.domains.mutationFailed.create": "新增網域失敗",
    "code.domains.mutationFailed.delete": "刪除網域失敗",
    "code.domains.preview": "預覽",
    "code.domains.role": "角色",
    "code.domains.scanAllAllBusy": "所有掃描已在執行中或已完成",
    "code.domains.scanAllFailed": "觸發掃描失敗",
    "code.domains.scanAllTriggered": "已觸發 {n} 項掃描",
    "code.domains.uploadCsv": "上傳 CSV",
    "code.error.loadFailed": "載入資料失敗",
    "code.findings.locations": "位置",
    "code.findings.subissues": "子問題",
    "code.findings.verifications": "驗證紀錄",
    "code.issues.autofixEligible": "可使用 AutoFix",
    "code.issues.autofixHint": "此發現可自動修補。前往修復頁籤查看可用的修補或執行 AutoFix。",
    "code.issues.autofixPatches": "AutoFix 修補",
    "code.issues.blastHigh": "高影響 \u2014 優先修復",
    "code.issues.blastLow": "低影響",
    "code.issues.blastMedium": "中等影響",
    "code.issues.blastRadius": "爆炸半徑",
    "code.issues.currentStatus": "目前狀態",
    "code.issues.firstDetected": "首次偵測",
    "code.issues.fixAll": "修復所有弱點",
    "code.issues.noAutoPR": "尚無自動 PR \u2014 對此儲存庫執行 AutoFix 以產生修補。",
    "code.issues.noContext": "此發現尚無跨維度訊號。",
    "code.issues.noContextHint": "執行更多掃描（滲透測試、汙點分析）以豐富此發現的可達性與風險上下文。",
    "code.issues.noFixAvailable": "此發現沒有可用的版本修復。",
    "code.issues.noIssuesDesc": "目前沒有安全問題",
    "code.issues.noIssuesTitle": "沒有問題",
    "code.issues.noVerifications": "尚無驗證執行。點擊驗證以開始。",
    "code.issues.openPRs": "開啟的 Pull Request",
    "code.issues.pentestVerdict": "滲透測試結果",
    "code.issues.reachability": "可達性",
    "code.issues.taintHint": "使用者控制的資料在未經過濾的情況下到達此程式碼路徑。",
    "code.issues.tldr": "摘要",
    "code.issues.to": "至",
    "code.issues.toFixAll": "修復全部",
    "code.issues.updateTo": "更新",
    "code.issues.vulnerabilities": "弱點",
    "code.onboarding.bitbucketDesc": "連接您的 Bitbucket 工作區以匯入儲存庫。",
    "code.onboarding.comingSoon": "即將推出",
    "code.onboarding.connectBitbucket": "連接 Bitbucket",
    "code.onboarding.connectGitlab": "連接 GitLab",
    "code.onboarding.feat1": "安全弱點與機密資訊",
    "code.onboarding.feat2": "死碼與複雜度分析",
    "code.onboarding.feat3": "相依性風險與授權問題",
    "code.onboarding.feat4": "攻擊面探索",
    "code.onboarding.githubDesc": "連接您的 GitHub 帳號以匯入儲存庫。",
    "code.onboarding.gitlabDesc": "連接您的 GitLab 實例以匯入專案。",
    "code.onboarding.noReposHint": "未選取儲存庫 \u2014 請至少選擇一個。",
    "code.onboarding.or": "或",
    "code.onboarding.scanDone": "設定完成！",
    "code.onboarding.scanDoneDesc": "結果將很快顯示在儀表板上。",
    "code.onboarding.scanningDesc": "正在分析您的儲存庫...",
    "code.onboarding.uploadDesc": "已使用 flyto-indexer 掃描？無需連接 GitHub 即可上傳結果。",
    "code.onboarding.uploadTitle": "上傳本機掃描",
    "code.onboarding.whatWeAnalyze": "我們分析的內容",
    "code.organization.addChild": "新增子節點",
    "code.organization.deleteNode": "刪除節點",
    "code.pentest.alreadyRunning": "掃描已在執行中",
    "code.pentest.emptyTitle": "尚無滲透測試目標",
    "code.pentest.noResultsTitle": "沒有測試目標",
    "code.pentest.queued": "已排入佇列",
    "code.pentest.rerunBtn": "重新執行",
    "code.pentest.runBtn": "執行滲透測試",
    "code.pentest.runHint": "對此目標執行 DAST 滲透測試",
    "code.pentest.runningBtn": "執行中...",
    "code.pentest.scanning": "掃描中...",
    "code.pentest.subtitle": "基於 OWASP 的安全檢查與 DAST 掃描",
    "code.pentest.title": "滲透測試",
    "code.prDialog.draft": "草稿",
    "code.prDialog.empty": "無開啟的 PR 資料 \u2014 快取可能尚未包含此儲存庫。",
    "code.prDialog.openOnGithub": "在 GitHub 上開啟",
    "code.prDialog.title": "與此發現相關的開啟 PR",
    "code.pulse.aiAutoGenerated": "資料更新時自動產生",
    "code.pulse.dimensions": "我們整合的維度",
    "code.pulse.emptyDesc": "目前沒有優先發現。執行掃描以開始跨所有維度填入結果。",
    "code.pulse.emptyTitle": "一切正常",
    "code.pulse.subtitle": "依爆炸半徑排名的跨維度優先發現",
    "code.repo.aiPrompt": "AI 提示",
    "code.repo.localHint": "執行 flyto-index scan . && flyto-index export . > scan.json，然後上傳檔案。",
    "code.repo.promptCopied": "已複製！",
    "code.repo.promptMissing": "無法產生 AI 提示 \u2014 掃描資料不完整",
    "code.repo.promptMissingHint": "缺少：",
    "code.repo.uploadNewScan": "上傳新掃描",
    "code.repo.uploadScan": "上傳掃描",
    "code.repo.uploadScanTitle": "上傳本機掃描",
    "code.repoDetail.projectInfo": "專案資訊",
    "code.repoDetail.verifyTargetsError": "載入驗證允許清單失敗",
    "code.repoList.connectRepos": "連接儲存庫",
    "code.repoList.emptyDesc": "連接您的 GitHub 或 GitLab 儲存庫，開始掃描安全問題、架構洞察等。",
    "code.repoList.emptyTitle": "尚未連接儲存庫",
    "code.repoList.noSearchResults": "沒有符合搜尋條件的儲存庫",
    "code.repoList.results": "筆結果",
    "code.repoList.searchPlaceholder": "依名稱、擁有者或語言搜尋儲存庫...",
    "code.repoList.subtitle": "管理並掃描已連接的儲存庫",
    "code.repoList.tryDifferent": "嘗試不同的搜尋字詞",
    "code.repoList.uploadScan": "上傳掃描結果",
    "code.risk.codeSecurity": "程式碼安全",
    "code.risk.compliance": "合規性",
    "code.risk.domain": "網域",
    "code.risk.highRisk": "高風險",
    "code.risk.infrastructure": "基礎架構",
    "code.risk.lowRisk": "低風險",
    "code.risk.secrets": "機密資訊",
    "code.risk.vulnerabilities": "弱點",
    "code.scoring.cspmScan": "雲端態勢",
    "code.scoring.malwareScan": "惡意相依套件",
    "code.scoring.runtimeEvents": "執行階段遙測",
    "code.settings.apiKeyName": "金鑰名稱（例如 CI Pipeline）",
    "code.settings.apiKeysDesc": "API 金鑰用於認證 CLI 掃描上傳。搭配 flyto-index 使用，無需授予伺服器存取原始碼的權限即可在本機掃描。",
    "code.settings.apiKeysTitle": "API 金鑰管理",
    "code.settings.copyKeyWarning": "請立即複製此金鑰 \u2014 之後將無法再次檢視。",
    "code.settings.createKey": "建立金鑰",
    "code.settings.disconnected": "已中斷連線",
    "code.settings.localUploadDesc": "上傳 flyto-indexer 的結果至新的或現有的儲存庫 \u2014 不需要 GitHub 令牌。",
    "code.settings.localUploadTitle": "本機掃描上傳",
    "code.settings.noKeys": "尚無 API 金鑰。建立一個以開始本機掃描。",
    "code.settings.subtitle": "設定",
    "code.settings.usage": "使用方式：",
    "code.upload.change": "變更",
    "code.upload.dropHint": "拖放 scan.json 至此處，或點擊選擇",
    "code.upload.needRepoName": "請輸入儲存庫名稱",
    "code.upload.noProfile": "無效的掃描檔案 \u2014 缺少設定檔",
    "code.upload.notJson": "請選擇 .json 檔案",
    "code.upload.parseError": "解析 JSON 檔案失敗",
    "code.upload.repoName": "儲存庫名稱",
    "code.upload.submit": "上傳並分析",
    "code.upload.success": "掃描已上傳 \u2014 正在背景處理中",
    "code.warroom.apiMethodDist": "方法",
    "code.warroom.apiSelectRepo": "選擇儲存庫以檢視路由",
    "code.warroom.apiTreeSub": "路由樹與方法分佈",
    "code.warroom.archOverviewSub": "跨儲存庫健康度、結構與風險訊號",
    "code.warroom.archOverviewTitle": "架構總覽",
    "code.warroom.archReposNone": "無儲存庫架構資料 \u2014 請先執行掃描。",
    "code.warroom.archReposSelect": "選擇儲存庫",
    "code.warroom.archReposSub": "各儲存庫健康度、結構與共用服務",
    "code.warroom.archSharedServices": "共用服務",
    "code.warroom.archUsedBy": "使用者",
    "code.warroom.cicdConnectTitle": "連接 GitHub 以檢視 CI/CD 資料",
    "code.warroom.cicdGateSub": "跨已連接儲存庫的工作流程執行",
    "code.warroom.cicdNoneTitle": "沒有 CI/CD 管線執行紀錄",
    "code.warroom.colIP": "來源 IP",
    "code.warroom.colPath": "路徑",
    "code.warroom.colRegion": "地區",
    "code.warroom.colSource": "來源",
    "code.warroom.colThreat": "威脅",
    "code.warroom.colType": "類型",
    "code.warroom.colWhen": "時間",
    "code.warroom.complexityNone": "未偵測到複雜函式。",
    "code.warroom.containerEmptyDesc": "容器掃描偵測 Docker 映像檔與基底層的弱點。連接包含 Dockerfile 的儲存庫並執行掃描以在此查看結果。",
    "code.warroom.containerNoFix": "無修復",
    "code.warroom.containerSub": "Docker 映像檔與基底層弱點",
    "code.warroom.cspmEmpty": "雲端態勢發現來自雲端設定快照。透過 API 上傳快照，或等待 SDK 即時掃描（規劃中）。僅連接程式碼儲存庫不會填入此檢視。",
    "code.warroom.cspmEmptyTitle": "沒有雲端態勢發現",
    "code.warroom.cspmSub": "來自快照上傳的雲端配置錯誤發現",
    "code.warroom.deadCodeSub": "跨所有儲存庫的未引用符號",
    "code.warroom.depsSub": "共用套件、集中風險與供應鏈暴露",
    "code.warroom.findingNoMatchTitle": "沒有符合的結果",
    "code.warroom.frameworksSub": "跨儲存庫框架情報與版本漂移",
    "code.warroom.iacEmptyDesc": "IaC 掃描檢查 Terraform、CloudFormation、Kubernetes manifest 與其他 IaC 檔案。對包含 IaC 檔案的儲存庫執行掃描以填入此檢視。",
    "code.warroom.iacSub": "Terraform、CloudFormation 與 Kubernetes 配置錯誤",
    "code.warroom.importsNone": "無匯入資料 \u2014 請先執行掃描。",
    "code.warroom.licenseNoRepos": "授權掃描在連接 GitHub 或 GitLab 儲存庫後自動開始。連接儲存庫以開始。",
    "code.warroom.licenseNoReposTitle": "尚未連接儲存庫",
    "code.warroom.licenseNotScannedTitle": "未發現授權問題",
    "code.warroom.licenseNotScannedYet": "尚未記錄授權問題。可能是最新掃描仍在執行中、已連接的儲存庫僅宣告安全授權，或無法擷取中繼資料。請在儲存庫檢視中確認掃描狀態。",
    "code.warroom.licenseSub": "授權合規問題",
    "code.warroom.liveViewClosed": "串流已關閉",
    "code.warroom.liveViewUnavailable": "即時檢視不可用",
    "code.warroom.malwareEmptyDesc": "惡意軟體掃描會針對已知的惡意套件資料庫檢查您的相依套件。對儲存庫執行掃描以填入此檢視。",
    "code.warroom.malwareNone": "未偵測到惡意相依套件",
    "code.warroom.malwareSub": "相依樹中的已知惡意套件",
    "code.warroom.noApiDataTitle": "無 API 資料",
    "code.warroom.noDataDesc": "無資料",
    "code.warroom.noReposDesc": "尚未連接儲存庫",
    "code.warroom.prActivitySub": "跨已連接儲存庫的 Pull Request",
    "code.warroom.prNoneTitle": "沒有找到 Pull Request",
    "code.warroom.reachEmptyDesc": "執行啟用汙點分析的掃描以填入此檢視。",
    "code.warroom.reachEmptyTitle": "無汙點分析資料",
    "code.warroom.redTeamSub": "多活動滲透測試與攻擊模擬",
    "code.warroom.runtimeEmpty": "執行階段事件來自安裝在您執行中應用程式的 SDK。在設定中建立組織 API 金鑰並安裝 SDK 以開始在此串流事件。",
    "code.warroom.runtimeEmptyTitle": "沒有執行階段事件",
    "code.warroom.runtimeSub": "來自正式環境 SDK 的即時攻擊偵測",
    "code.warroom.secActionSub": "跨所有儲存庫的未結發現",
    "code.warroom.secRepos": "儲存庫",
    "code.warroom.secSeverity": "嚴重程度",
    "code.warroom.verifyInvalidUrl": "必須是有效的 http:// 或 https:// URL",
    "code.warroom.verifyProbe1": "正在發送基準請求\u2026",
    "code.warroom.verifyProbe2": "正在發送酬載請求\u2026",
    "code.warroom.verifyProbe3": "正在比對回應\u2026",
    "code.warroom.verifyProgressHint": "通常在 10 秒內完成。",
}

filled = 0
for k, v in T.items():
    if k in zh and zh[k] == "":
        zh[k] = v
        filled += 1

data['translations'] = dict(sorted(zh.items()))

with open(zh_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
    f.write('\n')

remaining = sum(1 for v in data['translations'].values() if v == '')
print(f'Filled: {filled}')
print(f'Remaining empty: {remaining}')
print(f'Total: {len(data["translations"])}')
