"""Insert Attack Paths i18n keys into 4 primary locales.

Run from the flyto-i18n repo root:
    python3 scripts/one-off/add_attackpath_keys.py
"""
import json
from pathlib import Path

LOCALES = {
    "en": {
        "nav.attack_paths": "Attack Paths",

        "code.attackpath.title":    "Attack Paths",
        "code.attackpath.subtitle": "Where would an attacker start, and why — converged from existing recon signals into the top initial-access hypotheses worth red-team validation.",
        "code.attackpath.expand":   "Show evidence, red-team validation & restrictions",
        "code.attackpath.collapse": "Hide details",
        "code.attackpath.disclaimer": "Recon mode only — no logins, no payloads, no brute-force, no external API calls beyond the cached recon data. All candidates are hypotheses to be authorised before red-team validation.",

        "code.attackpath.confidence.label":    "Confidence",
        "code.attackpath.confidence.tooltip":  "How plausible the hypothesis is — built from external exposure plus multi-source signal concurrence.",
        "code.attackpath.readiness.label":     "Readiness",
        "code.attackpath.readiness.tooltip":   "Whether the red team can legally and safely test this candidate in the current engagement.",

        "code.attackpath.filter.confidence.low":    "All confidences",
        "code.attackpath.filter.confidence.medium": "Medium & high only",
        "code.attackpath.filter.confidence.high":   "High confidence only",
        "code.attackpath.sort.confidence": "Sort by confidence",
        "code.attackpath.sort.readiness":  "Sort by readiness",
        "code.attackpath.sort.why_now":    "Sort by recency",

        "code.attackpath.cat.initial_access":       "Initial Access",
        "code.attackpath.cat.web_app":              "External Web Portal",
        "code.attackpath.cat.information_exposure": "Public Information Exposure",
        "code.attackpath.cat.email_spoofing":       "Email Spoofing",
        "code.attackpath.cat.supply_chain":         "Third-party Supply Chain",

        "code.attackpath.credential_initial_access.title":    "Credential-based Initial Access",
        "code.attackpath.customer_portal_webapp.title":       "External Web Portal",
        "code.attackpath.public_code_exposure.title":         "Public Information Exposure",
        "code.attackpath.email_spoofing_setup.title":         "Email Spoofing Risk",
        "code.attackpath.supply_chain_third_party.title":     "Third-party Supply Chain",

        "code.attackpath.section.risk_logic":   "Risk logic",
        "code.attackpath.section.evidence":     "Supporting evidence",
        "code.attackpath.section.red_team":     "Red-team validation",
        "code.attackpath.section.restrictions": "Recon-mode restrictions",

        "code.attackpath.summary.external_assets": "External assets",
        "code.attackpath.summary.leak_signals":    "Leak signals",
        "code.attackpath.summary.tech":            "Tech fingerprints",
        "code.attackpath.summary.pentests":        "Pentest projects",
        "code.attackpath.summary.whynow_30d":      "Recent signals (30d)",
        "code.attackpath.summary.shown":           "{n} of {total} candidates shown",

        "code.attackpath.empty.title":  "No candidates match the current filter",
        "code.attackpath.empty.low":    "No attack-path hypotheses surfaced. Run a discovery scan or connect repos to feed the signal collectors.",
        "code.attackpath.empty.medium": "Nothing at medium+ confidence. Switch to All to see lower-confidence candidates worth a manual review.",

        "code.attackpath.whynow.today":                    "today",
        "code.attackpath.whynow.dmarc_none":               "DMARC policy is currently p=none",
        "code.attackpath.whynow.credential_leak_recent":   "Credential exposure observed",
        "code.attackpath.whynow.portal_new":               "Login portal first observed this week",
        "code.attackpath.whynow.webapp_new":               "Web app first observed this week",
        "code.attackpath.whynow.public_leak_recent":       "Public exposure observed",
        "code.attackpath.whynow.external_issue_recent":    "Recent open external issue",
    },
    "zh-TW": {
        "nav.attack_paths": "攻擊路徑",
        "code.attackpath.title":    "攻擊路徑",
        "code.attackpath.subtitle": "攻擊者最可能從哪裡開始，以及為什麼——把現有的偵察訊號收斂成最值得紅軍驗證的初始入侵假設。",
        "code.attackpath.expand":   "展開證據、紅軍驗證與限制",
        "code.attackpath.collapse": "收起詳情",
        "code.attackpath.disclaimer": "僅限偵察模式——不登入、不送 payload、不爆破、不打外部 API。所有候選都只是假設，紅軍驗證前需取得授權。",
        "code.attackpath.confidence.label":    "信心",
        "code.attackpath.confidence.tooltip":  "這條假設成立的可能性——由外部曝險與多來源訊號一致性綜合而成。",
        "code.attackpath.readiness.label":     "可驗證度",
        "code.attackpath.readiness.tooltip":   "紅軍在當前授權範圍內能否合法、安全地驗證這條候選路徑。",
        "code.attackpath.filter.confidence.low":    "顯示全部",
        "code.attackpath.filter.confidence.medium": "中等以上",
        "code.attackpath.filter.confidence.high":   "僅高信心",
        "code.attackpath.sort.confidence": "依信心排序",
        "code.attackpath.sort.readiness":  "依可驗證度排序",
        "code.attackpath.sort.why_now":    "依時效排序",
        "code.attackpath.cat.initial_access":       "初始入侵",
        "code.attackpath.cat.web_app":              "外部 Web 入口",
        "code.attackpath.cat.information_exposure": "公開資訊暴露",
        "code.attackpath.cat.email_spoofing":       "郵件偽冒",
        "code.attackpath.cat.supply_chain":         "第三方供應鏈",
        "code.attackpath.credential_initial_access.title":    "帳號型初始入侵",
        "code.attackpath.customer_portal_webapp.title":       "外部 Web 入口",
        "code.attackpath.public_code_exposure.title":         "公開資訊暴露",
        "code.attackpath.email_spoofing_setup.title":         "郵件偽冒風險",
        "code.attackpath.supply_chain_third_party.title":     "第三方供應鏈入口",
        "code.attackpath.section.risk_logic":   "風險邏輯",
        "code.attackpath.section.evidence":     "支持證據",
        "code.attackpath.section.red_team":     "紅軍驗證",
        "code.attackpath.section.restrictions": "偵察模式限制",
        "code.attackpath.summary.external_assets": "外部資產",
        "code.attackpath.summary.leak_signals":    "外洩訊號",
        "code.attackpath.summary.tech":            "技術指紋",
        "code.attackpath.summary.pentests":        "紅軍演練專案",
        "code.attackpath.summary.whynow_30d":      "近 30 天新訊號",
        "code.attackpath.summary.shown":           "顯示 {n} / {total} 條候選",
        "code.attackpath.empty.title":  "目前篩選下沒有候選",
        "code.attackpath.empty.low":    "尚未收斂出攻擊路徑假設。執行 Discovery 掃描或連接 repo 以餵入訊號收集器。",
        "code.attackpath.empty.medium": "中等以上信心無候選。切換到「顯示全部」可看到較低信心、值得人工複核的候選。",
        "code.attackpath.whynow.today":                    "今天",
        "code.attackpath.whynow.dmarc_none":               "DMARC 政策目前為 p=none",
        "code.attackpath.whynow.credential_leak_recent":   "觀察到憑證外洩",
        "code.attackpath.whynow.portal_new":               "本週首次觀察到登入入口",
        "code.attackpath.whynow.webapp_new":               "本週首次觀察到 Web 應用",
        "code.attackpath.whynow.public_leak_recent":       "近期公開暴露",
        "code.attackpath.whynow.external_issue_recent":    "近期未解決的外部問題",
    },
    "zh-CN": {
        "nav.attack_paths": "攻击路径",
        "code.attackpath.title":    "攻击路径",
        "code.attackpath.subtitle": "攻击者最可能从哪里开始，以及为什么——将现有的侦察信号收敛为最值得红军验证的初始入侵假设。",
        "code.attackpath.expand":   "展开证据、红军验证与限制",
        "code.attackpath.collapse": "收起详情",
        "code.attackpath.disclaimer": "仅限侦察模式——不登录、不发送 payload、不爆破、不调用外部 API。所有候选都只是假设，红军验证前需取得授权。",
        "code.attackpath.confidence.label":    "信心",
        "code.attackpath.confidence.tooltip":  "假设成立的可能性——由外部曝险与多源信号一致性综合而成。",
        "code.attackpath.readiness.label":     "可验证度",
        "code.attackpath.readiness.tooltip":   "红军在当前授权范围内能否合法、安全地验证这条候选路径。",
        "code.attackpath.filter.confidence.low":    "显示全部",
        "code.attackpath.filter.confidence.medium": "中等及以上",
        "code.attackpath.filter.confidence.high":   "仅高信心",
        "code.attackpath.sort.confidence": "按信心排序",
        "code.attackpath.sort.readiness":  "按可验证度排序",
        "code.attackpath.sort.why_now":    "按时效排序",
        "code.attackpath.cat.initial_access":       "初始入侵",
        "code.attackpath.cat.web_app":              "外部 Web 入口",
        "code.attackpath.cat.information_exposure": "公开信息暴露",
        "code.attackpath.cat.email_spoofing":       "邮件冒充",
        "code.attackpath.cat.supply_chain":         "第三方供应链",
        "code.attackpath.credential_initial_access.title":    "账号型初始入侵",
        "code.attackpath.customer_portal_webapp.title":       "外部 Web 入口",
        "code.attackpath.public_code_exposure.title":         "公开信息暴露",
        "code.attackpath.email_spoofing_setup.title":         "邮件冒充风险",
        "code.attackpath.supply_chain_third_party.title":     "第三方供应链入口",
        "code.attackpath.section.risk_logic":   "风险逻辑",
        "code.attackpath.section.evidence":     "支持证据",
        "code.attackpath.section.red_team":     "红军验证",
        "code.attackpath.section.restrictions": "侦察模式限制",
        "code.attackpath.summary.external_assets": "外部资产",
        "code.attackpath.summary.leak_signals":    "泄漏信号",
        "code.attackpath.summary.tech":            "技术指纹",
        "code.attackpath.summary.pentests":        "红军演练项目",
        "code.attackpath.summary.whynow_30d":      "近 30 天新信号",
        "code.attackpath.summary.shown":           "显示 {n} / {total} 条候选",
        "code.attackpath.empty.title":  "当前筛选下没有候选",
        "code.attackpath.empty.low":    "尚未收敛出攻击路径假设。执行 Discovery 扫描或连接 repo 以喂入信号收集器。",
        "code.attackpath.empty.medium": "中等以上信心无候选。切换到「显示全部」查看较低信心、值得人工复核的候选。",
        "code.attackpath.whynow.today":                    "今天",
        "code.attackpath.whynow.dmarc_none":               "DMARC 策略目前为 p=none",
        "code.attackpath.whynow.credential_leak_recent":   "观察到凭据泄漏",
        "code.attackpath.whynow.portal_new":               "本周首次观察到登录入口",
        "code.attackpath.whynow.webapp_new":               "本周首次观察到 Web 应用",
        "code.attackpath.whynow.public_leak_recent":       "近期公开暴露",
        "code.attackpath.whynow.external_issue_recent":    "近期未解决的外部问题",
    },
    "ja": {
        "nav.attack_paths": "攻撃経路",
        "code.attackpath.title":    "攻撃経路",
        "code.attackpath.subtitle": "攻撃者がどこから入るか、なぜか — 既存の偵察信号を、レッドチーム検証に値する初期侵入仮説に収斂させます。",
        "code.attackpath.expand":   "証拠、レッドチーム検証、制約を表示",
        "code.attackpath.collapse": "詳細を隠す",
        "code.attackpath.disclaimer": "偵察モードのみ — ログイン・ペイロード送信・ブルートフォース・外部 API 呼び出しは行いません。すべての候補は仮説であり、検証前に承認が必要です。",
        "code.attackpath.confidence.label":    "信頼度",
        "code.attackpath.confidence.tooltip":  "仮説の妥当性 — 外部露出度と多元的シグナル一致から算出。",
        "code.attackpath.readiness.label":     "検証可能性",
        "code.attackpath.readiness.tooltip":   "現在の契約範囲でレッドチームが合法かつ安全に検証できるか。",
        "code.attackpath.filter.confidence.low":    "すべて表示",
        "code.attackpath.filter.confidence.medium": "中以上のみ",
        "code.attackpath.filter.confidence.high":   "高のみ",
        "code.attackpath.sort.confidence": "信頼度で並び替え",
        "code.attackpath.sort.readiness":  "検証可能性で並び替え",
        "code.attackpath.sort.why_now":    "新着順で並び替え",
        "code.attackpath.cat.initial_access":       "初期侵入",
        "code.attackpath.cat.web_app":              "外部 Web エントリー",
        "code.attackpath.cat.information_exposure": "公開情報の漏洩",
        "code.attackpath.cat.email_spoofing":       "なりすましメール",
        "code.attackpath.cat.supply_chain":         "サードパーティ依存",
        "code.attackpath.credential_initial_access.title":    "資格情報型初期侵入",
        "code.attackpath.customer_portal_webapp.title":       "外部 Web エントリー",
        "code.attackpath.public_code_exposure.title":         "公開情報の漏洩",
        "code.attackpath.email_spoofing_setup.title":         "なりすましメールのリスク",
        "code.attackpath.supply_chain_third_party.title":     "サードパーティ依存",
        "code.attackpath.section.risk_logic":   "リスク論理",
        "code.attackpath.section.evidence":     "裏付け証拠",
        "code.attackpath.section.red_team":     "レッドチーム検証",
        "code.attackpath.section.restrictions": "偵察モードの制約",
        "code.attackpath.summary.external_assets": "外部資産",
        "code.attackpath.summary.leak_signals":    "漏洩シグナル",
        "code.attackpath.summary.tech":            "技術フィンガープリント",
        "code.attackpath.summary.pentests":        "ペネトレーション案件",
        "code.attackpath.summary.whynow_30d":      "30 日以内の新シグナル",
        "code.attackpath.summary.shown":           "{total} 件中 {n} 件を表示",
        "code.attackpath.empty.title":  "現在のフィルターに該当する候補はありません",
        "code.attackpath.empty.low":    "攻撃経路の仮説が収斂されていません。Discovery スキャンを実行するかリポジトリを接続してください。",
        "code.attackpath.empty.medium": "中以上の信頼度に候補がありません。「すべて表示」に切り替えると、手動レビューに値する低信頼度の候補が見られます。",
        "code.attackpath.whynow.today":                    "今日",
        "code.attackpath.whynow.dmarc_none":               "DMARC ポリシーが現在 p=none",
        "code.attackpath.whynow.credential_leak_recent":   "資格情報の漏洩を観測",
        "code.attackpath.whynow.portal_new":               "今週初めてログインポータルを観測",
        "code.attackpath.whynow.webapp_new":               "今週初めて Web アプリを観測",
        "code.attackpath.whynow.public_leak_recent":       "最近の公開漏洩",
        "code.attackpath.whynow.external_issue_recent":    "最近未解決の外部課題",
    },
}

root = Path("locales/code")
for locale, kvs in LOCALES.items():
    p = root / locale / "code.json"
    obj = json.loads(p.read_text(encoding="utf-8"))
    t = obj.setdefault("translations", {})
    added = 0
    for k, v in kvs.items():
        if k not in t:
            added += 1
        t[k] = v
    obj["translations"] = dict(sorted(t.items()))
    p.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{locale}: +{added} new, {len(kvs)} touched")
