#!/usr/bin/env python3
"""Fill the 2026-05 Japanese Code gap batch without replacing existing text."""

# fill-ja-code-gaps.py — one-off, append-only ja gap filler.
# Adds machine-translated entries for keys present in en/code.json
# but missing/empty in ja/code.json. Existing ja values are NEVER
# overwritten. Translations are domain-aware UI strings; treat as
# baseline — a native Japanese reviewer should still pass over them.

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
JA = ROOT / 'locales' / 'code' / 'ja' / 'code.json'

# 538 translations covering the 2026-05 batch of new keys.
T = {
    # compliance
    "code.compliance.all": "すべて",
    "code.compliance.backToFrameworks": "フレームワーク一覧に戻る",
    "code.compliance.controlId": "コントロール ID",
    "code.compliance.controlName": "コントロール",
    "code.compliance.details": "詳細",
    "code.compliance.emptyDesc": "スキャンを実行してコンプライアンス評価結果を生成します。",
    "code.compliance.emptyTitle": "コンプライアンスデータがありません",
    "code.compliance.fail": "不合格",
    "code.compliance.failed": "失敗",
    "code.compliance.filterStatus": "ステータスで絞り込み",
    "code.compliance.noControls": "フィルタに一致するコントロールはありません",
    "code.compliance.partial": "部分的",
    "code.compliance.pass": "合格",
    "code.compliance.passed": "合格済み",
    "code.compliance.status": "ステータス",
    "code.compliance.subtitle": "SOC2、ISO 27001、PCI-DSS、OWASP、GDPR、HIPAA、NIST のフレームワーク準拠状況",
    "code.compliance.title": "コンプライアンスダッシュボード",
    "code.compliance.total": "合計",

    # cross
    "code.cross.allPassed": "すべてのドメインで全チェックが合格しました。",
    "code.cross.clean": "クリーン",
    "code.cross.domain": "ドメイン",
    "code.cross.domainsAffected": "ドメイン",
    "code.cross.domainsWithFailures": "件のドメインに失敗あり。",
    "code.cross.domainsWithWarnings": "件のドメインに警告あり。",
    "code.cross.fail": "失敗",
    "code.cross.failed": "失敗",
    "code.cross.issues": "問題",
    "code.cross.mostCommon": "最も多い",
    "code.cross.noData": "データなし",
    "code.cross.pass": "合格",
    "code.cross.recommendations": "推奨事項",
    "code.cross.scanned": "スキャン済み",
    "code.cross.status": "ステータス",
    "code.cross.total": "合計",
    "code.cross.warning": "警告",

    # dashboard
    "code.dashboard.actionHigh": "{n} 件の高重大度の問題に対応が必要です",
    "code.dashboard.blastRadius": "影響範囲",
    "code.dashboard.changesInPeriod": "変動",
    "code.dashboard.collapseTrend": "折りたたむ",
    "code.dashboard.effectiveDate": "有効日",
    "code.dashboard.expandTrend": "トレンド全体を表示",
    "code.dashboard.fixCriticalCVE": "{pkg} の重大な CVE を修正",
    "code.dashboard.fixTaintFlow": "テイントフローを修正: {source} → {sink}",
    "code.dashboard.gradeChanges": "グレード変動",
    "code.dashboard.gradeDist": "グレード分布",
    "code.dashboard.highestOn": "最高値: {date}",
    "code.dashboard.lowestOn": "最低値: {date}",
    "code.dashboard.netChange": "正味変動",
    "code.dashboard.noActionsNeeded": "緊急の対応は不要です",
    "code.dashboard.noGradeChanges": "この期間にグレード変動はありません",
    "code.dashboard.noGradeData": "グレードデータがありません",
    "code.dashboard.noPulseItems": "緊急対応項目はありません — セキュリティ態勢は安定しています",
    "code.dashboard.noTrendData": "トレンドチャートを描画するには十分なデータがありません。スコアは各スキャン後に記録されます。",
    "code.dashboard.pointDecrease": "{n} ポイント低下",
    "code.dashboard.pointIncrease": "{n} ポイント上昇",
    "code.dashboard.priorityActions": "優先対応事項",
    "code.dashboard.priorityActionsDesc": "今すぐ最も効果的な修正",
    "code.dashboard.pulseAutofix": "AutoFix",
    "code.dashboard.pulsePR": "PR",
    "code.dashboard.pulsePentest": "ペンテスト",
    "code.dashboard.pulseTaint": "テイント",
    "code.dashboard.pulseTop": "対応すべき項目",
    "code.dashboard.pulseTop5": "影響範囲が大きい主要な検出結果",
    "code.dashboard.pulseTopDesc": "影響範囲の大きい順に並べ替え",
    "code.dashboard.ratingChanges": "レーティング変動",
    "code.dashboard.reposBreakdown": "リポジトリ",
    "code.dashboard.rotateSecret": "{file} 内の漏洩した {type} をローテーション",
    "code.dashboard.scoreSummary": "スコアサマリ",
    "code.dashboard.scoreTrend": "スコアトレンド",
    "code.dashboard.scoreTrendTitle": "セキュリティレーティングの変動",
    "code.dashboard.scoringBreakdown": "スコアリング内訳",
    "code.dashboard.upgradePackage": "{repo} の {pkg} をアップグレード — {count} 件の CVE を修正",
    "code.dashboard.viewAllPulse": "Pulse ですべて表示",
    "code.dashboard.why": "なぜ?",

    # dast
    "code.dast.allChecksPassed": "すべてのチェックに合格",
    "code.dast.score.allSet": "問題なし",
    "code.dast.score.clean": "クリーン",
    "code.dast.score.critical": "重大",
    "code.dast.score.email": "メール",
    "code.dast.score.expired": "期限切れ",
    "code.dast.score.files": "ファイル",
    "code.dast.score.found": "検出",
    "code.dast.score.headers": "ヘッダー",
    "code.dast.score.issues": "問題",
    "code.dast.score.missing": "未設定",
    "code.dast.score.no": "いいえ",
    "code.dast.score.none": "なし",
    "code.dast.score.ok": "OK",
    "code.dast.score.ports": "ポート",
    "code.dast.score.risky": "リスクあり",
    "code.dast.score.ssl": "SSL",
    "code.dast.score.total": "合計",
    "code.dast.score.waf": "WAF",
    "code.dast.score.yes": "はい",
    "code.dast.tab.ai": "AI",
    "code.dast.tab.api": "API",
    "code.dast.tab.intelligence": "インテリジェンス",
    "code.dast.tab.network": "ネットワーク",
    "code.dast.tab.pagespeed": "ページ速度",
    "code.dast.tab.security": "セキュリティ",

    # dim (per-dimension scanner views)
    "code.dim.clean": "クリーン",
    "code.dim.closed": "閉鎖",
    "code.dim.configured": "設定済み",
    "code.dim.disabled": "無効",
    "code.dim.dns.empty": "DNS セキュリティデータがありません",
    "code.dim.dns.emptyDesc": "ドメインスキャンを実行して DNS セキュリティレコードを確認します。",
    "code.dim.dns.fixAXFR": "DNS ゾーン転送 (AXFR) を承認済みのセカンダリ DNS サーバーのみに制限してください。",
    "code.dim.dns.fixCAA": "CAA レコードを追加し、ドメインに証明書を発行できる認証局を制限してください。",
    "code.dim.dns.fixDKIM": "メールプロバイダで DKIM を設定し、DNS TXT レコードを公開してください。",
    "code.dim.dns.fixDMARC": "_dmarc.yourdomain.com に DMARC TXT を追加: v=DMARC1; p=none",
    "code.dim.dns.fixDNSSEC": "ドメインレジストラで DNSSEC を有効化してください。多くはワンクリックで対応可能です。",
    "code.dim.dns.fixSPF": "SPF TXT レコードを追加: v=spf1 include:_spf.google.com ~all",
    "code.dim.dns.noZoneTransfer": "ゾーン転送なし",
    "code.dim.dns.sub": "全ドメインの DNSSEC、SPF、DMARC、DKIM、CAA レコード",
    "code.dim.dns.title": "DNS セキュリティ",
    "code.dim.email.empty": "メールセキュリティデータがありません",
    "code.dim.email.emptyDesc": "ドメインスキャンを実行してメールセキュリティ設定を確認します。",
    "code.dim.email.fixMX": "ドメインに MX レコードがありません — メールが設定されていません。",
    "code.dim.email.fixScore": "SPF、DKIM、DMARC を設定してください。診断には mxtoolbox.com を使用できます。",
    "code.dim.email.mx": "MX レコード",
    "code.dim.email.score": "スコア ≥ 70",
    "code.dim.email.sub": "全ドメインの SPF、DKIM、DMARC 整合性とメール認証",
    "code.dim.email.title": "メールセキュリティ",
    "code.dim.enabled": "有効",
    "code.dim.exposed": "公開",
    "code.dim.found": "検出",
    "code.dim.headers.empty": "HTTP データがありません",
    "code.dim.headers.emptyDesc": "ドメインスキャンを実行して HTTP セキュリティヘッダーを確認します。",
    "code.dim.headers.fixCSP": "Content-Security-Policy ヘッダーを追加してください。report-only モードから開始することを推奨します。",
    "code.dim.headers.fixHSTS": "Strict-Transport-Security: max-age=31536000; includeSubDomains を追加してください。",
    "code.dim.headers.fixPoweredBy": "X-Powered-By を削除してください — バックエンドフレームワークが露出します。",
    "code.dim.headers.fixServer": "Server ヘッダーを削除して Web サーバーのバージョン情報の漏洩を防いでください。",
    "code.dim.headers.fixXCT": "X-Content-Type-Options: nosniff を追加してください。",
    "code.dim.headers.fixXFO": "クリックジャッキング対策として X-Frame-Options: DENY を追加してください。",
    "code.dim.headers.noPoweredBy": "X-Powered-By なし",
    "code.dim.headers.noServer": "Server なし",
    "code.dim.headers.sub": "HTTP セキュリティヘッダーとサーバー情報の漏洩",
    "code.dim.headers.title": "Web セキュリティヘッダー",
    "code.dim.hidden": "非表示",
    "code.dim.missing": "未設定",
    "code.dim.none": "なし",
    "code.dim.notFound": "未検出",
    "code.dim.ports.empty": "ポートスキャンデータがありません",
    "code.dim.ports.emptyDesc": "ドメインスキャンを実行して開放ポートを確認します。",
    "code.dim.ports.fixDB": "データベースポートを公開インターネットから閉じてください。VPN またはプライベートネットワークを使用してください。",
    "code.dim.ports.fixFTP": "ポート 21 (FTP) を閉じてください。代わりに SFTP (ポート 22) を使用してください。",
    "code.dim.ports.fixRDP": "RDP (3389) と VNC (5900) を閉じてください。リモートアクセスには VPN を使用してください。",
    "code.dim.ports.fixSMB": "ポート 445 (SMB/CIFS) を閉じてください。Windows ファイル共有を公開しないでください。",
    "code.dim.ports.fixTelnet": "ポート 23 (Telnet) を閉じてください。SSH (ポート 22) を使用してください。",
    "code.dim.ports.noDB": "DB ポートなし",
    "code.dim.ports.noFTP": "FTP なし",
    "code.dim.ports.noRDP": "RDP/VNC なし",
    "code.dim.ports.noSMB": "SMB なし",
    "code.dim.ports.noTelnet": "Telnet なし",
    "code.dim.ports.sub": "全ドメインの開放ポートと危険なサービス",
    "code.dim.ports.title": "ネットワーク公開状況",
    "code.dim.safe": "安全",
    "code.dim.sensitive.clean": "クリーン",
    "code.dim.sensitive.empty": "機微ファイルデータがありません",
    "code.dim.sensitive.emptyDesc": "スキャンを実行して機微ファイル (.env、.git、バックアップ) の公開を確認します。",
    "code.dim.sensitive.fixCritical": ".env、.git、データベースバックアップ、設定ファイルへのアクセスを削除または制限してください。",
    "code.dim.sensitive.fixFiles": "公開ファイルをすべて確認してください。機微パスをブロックするサーバールールを追加してください。",
    "code.dim.sensitive.noCritical": "重要ファイルなし",
    "code.dim.sensitive.sub": "公開された設定ファイル、バックアップ、開発成果物",
    "code.dim.sensitive.title": "機微ファイルの公開",
    "code.dim.set": "設定済み",
    "code.dim.ssl.cipher": "強力な暗号スイート",
    "code.dim.ssl.empty": "SSL データがありません",
    "code.dim.ssl.emptyDesc": "ドメインスキャンを実行して SSL/TLS 証明書を確認します。",
    "code.dim.ssl.expired": "期限切れ",
    "code.dim.ssl.fixCipher": "ECDHE+AESGCM 系の暗号スイートを使用してください。RC4、DES、NULL、EXPORT を無効化してください。",
    "code.dim.ssl.fixExpiry": "証明書を有効期限前に更新してください。Let\\'s Encrypt の使用を推奨します。",
    "code.dim.ssl.fixHSTS": "Strict-Transport-Security ヘッダーを追加してください。テスト後 hstspreload.org に登録してください。",
    "code.dim.ssl.fixSelfSigned": "自己署名証明書を信頼された CA (Let\\'s Encrypt 等) に置き換えてください。",
    "code.dim.ssl.fixTLS": "サーバー設定で TLS 1.0 と 1.1 を無効化してください。TLS 1.2 と 1.3 のみ許可してください。",
    "code.dim.ssl.missing": "未設定",
    "code.dim.ssl.notSelfSigned": "自己署名ではない",
    "code.dim.ssl.preloaded": "プリロード済み",
    "code.dim.ssl.sub": "全ドメインの証明書有効性、プロトコルバージョン、暗号強度",
    "code.dim.ssl.title": "SSL / TLS の健全性",
    "code.dim.ssl.valid": "有効",
    "code.dim.threat.empty": "脅威インテリジェンスデータがありません",
    "code.dim.threat.emptyDesc": "スキャンを実行してドメインを脅威インテリジェンスフィードと照合します。",
    "code.dim.threat.fixC2": "C2 兆候が検出されました。侵害されたサーバーがないか直ちに調査してください。",
    "code.dim.threat.fixReputation": "IP がブロックリスト (MXToolbox、AbuseIPDB) に登録されていないか確認してください。",
    "code.dim.threat.noC2": "C2 なし",
    "code.dim.threat.reputation": "レピュテーション",
    "code.dim.threat.sub": "全ドメインの C2 兆候、マルウェア URL、IP レピュテーション",
    "code.dim.threat.title": "脅威インテリジェンス",
    "code.dim.vulnerable": "脆弱",
    "code.dim.waf.behavior": "挙動",
    "code.dim.waf.detected": "WAF を検出",
    "code.dim.waf.empty": "WAF データがありません",
    "code.dim.waf.emptyDesc": "スキャンを実行してドメインの WAF 有無を確認します。",
    "code.dim.waf.fixWAF": "WAF を導入してください: Cloudflare (無料)、AWS WAF、または OWASP CRS を備えた ModSecurity。",
    "code.dim.waf.sub": "全本番ドメインの Web アプリケーションファイアウォール検出",
    "code.dim.waf.title": "WAF と保護",

    # domains / exposure activity / brand
    "code.domains.scanning": "スキャン中...",
    "code.exposure.activity.burstEvents": "件のイベント",
    "code.exposure.activity.burstHint": "スキャンキャンペーンまたは協調攻撃の可能性があります。下記のカテゴリ別フィルタを確認してください。",
    "code.exposure.activity.burstIn": "ウィンドウ",
    "code.exposure.activity.burstMinutes": "分",
    "code.exposure.activity.burstPrefix": "急増",
    "code.exposure.brand.detectedAt": "検出日時",
    "code.exposure.brand.downloadPDF": "PDF をダウンロード",
    "code.exposure.brand.homograph": "ホモグラフ",
    "code.exposure.brand.letterPlaceholder": "テンプレートが読み込まれるとここに通知文が表示されます…",
    "code.exposure.brand.noThreats": "なりすまし脅威は検出されませんでした",
    "code.exposure.brand.noThreatsDesc": "ドメインなりすましの脅威は確認されていません",
    "code.exposure.brand.pdfWorking": "生成中...",
    "code.exposure.brand.resetLetter": "テンプレートにリセット",
    "code.exposure.brand.resolvesTo": "解決先",
    "code.exposure.brand.subtitle": "近似ドメインとフィッシング脅威の監視",
    "code.exposure.brand.title": "ブランド保護",
    "code.exposure.brand.tldSwap": "TLD 置換",
    "code.exposure.brand.totalDetected": "{n} 件の近似ドメインを検出",
    "code.exposure.brand.typosquat": "タイポスクワット",
    "code.exposure.brand.vsOriginal": "対象",
    "code.exposure.threat.breachAccounts": "{n} 件のアカウントが侵害",
    "code.exposure.threat.breachCount": "{n} 件の侵害を検出",
    "code.exposure.threat.breachDataTypes": "漏洩したデータ",
    "code.exposure.threat.breachDate": "侵害日",
    "code.exposure.threat.breachSection": "侵害公開",
    "code.exposure.threat.breachSource": "ソース",
    "code.exposure.threat.breachVerified": "検証済み",
    "code.exposure.threat.c2Confidence": "信頼度",
    "code.exposure.threat.c2Count": "{n} 件の兆候を検出",
    "code.exposure.threat.c2FirstSeen": "初回検出",
    "code.exposure.threat.c2Malware": "マルウェア",
    "code.exposure.threat.c2Section": "C2 / IOC 兆候",
    "code.exposure.threat.ipPorts": "開放ポート",
    "code.exposure.threat.ipScore": "リスクスコア",
    "code.exposure.threat.ipSection": "IP レピュテーション",
    "code.exposure.threat.ipVulns": "既知の CVE",
    "code.exposure.threat.noBreaches": "侵害公開は検出されませんでした",
    "code.exposure.threat.noC2": "C2 兆候は検出されませんでした",
    "code.exposure.threat.noIP": "IP レピュテーションデータがありません",
    "code.exposure.threat.subtitle": "ドメイン横断の侵害公開、C2 兆候、IP レピュテーション",
    "code.exposure.threat.title": "脅威インテリジェンス",

    # external posture
    "code.external.actionPlan": "アクションプラン",
    "code.external.actionPlanSub": "優先度順の修正手順 — 何を最初に直すか、どう直すか",
    "code.external.actionPlanTitle": "アクションプラン",
    "code.external.allIssues": "未対応の問題すべて",
    "code.external.assets": "資産",
    "code.external.avgRisk": "平均リスクスコア",
    "code.external.avgRiskScore": "平均リスクスコア",
    "code.external.breached": "侵害あり",
    "code.external.budgetExhausted": "予算超過",
    "code.external.budgetInactive": "ポリシー停止中",
    "code.external.budgetRemaining": "残り",
    "code.external.category": "カテゴリ",
    "code.external.clean": "クリーン",
    "code.external.copyMarkdown": "Markdown をコピー",
    "code.external.critHighIssues": "重大 + 高重大度",
    "code.external.criticalRisk": "重大リスク",
    "code.external.criticalVendors": "重大リスク",
    "code.external.criticality": "重要度",
    "code.external.domainStatus": "ドメインステータス",
    "code.external.domains": "ドメイン",
    "code.external.download": ".md をダウンロード",
    "code.external.errorBudget": "エラーバジェット",
    "code.external.errorBudgetHint": "四半期ごと、重大度ごとの SLA 違反許容量 — 有効化するには設定でポリシーを宣言してください。",
    "code.external.estFix": "想定工数",
    "code.external.exceededWindow": "修復期限を超過",
    "code.external.exceedingWindow": "修復期限を超過中",
    "code.external.exportPDF": "PDF をエクスポート",
    "code.external.forecast30d": "30 日予測",
    "code.external.forecastHint": "線形トレンド + 7 日季節性による 30 日予測。期間が長いほど信頼区間が広くなり、短期ほど精度が高い。",
    "code.external.howToFix": "修正方法:",
    "code.external.ifAllFixed": "すべて修正した場合",
    "code.external.intelSub": "検出結果、修復ガイダンス、サプライチェーンインテリジェンス",
    "code.external.intelTitle": "ドメインインテリジェンス",
    "code.external.issues": "件",
    "code.external.issuesRemediation": "検出結果と修復",
    "code.external.lastScan": "最終スキャン",
    "code.external.mttrTrend": "MTTR トレンド",
    "code.external.mttrTrendHint": "直近 4 週の P50 と前の 4 週との比較 — 負の値は改善を示します",
    "code.external.neverScanned": "未スキャン",
    "code.external.nextScan": "次回",
    "code.external.noActions": "問題なし",
    "code.external.noActionsDesc": "未対応の問題はありません。外部セキュリティ態勢はクリーンです。",
    "code.external.noDomains": "ドメインが設定されていません",
    "code.external.noDomainsDesc": "Domains ビューでドメインを追加して外部セキュリティ監視を開始してください。",
    "code.external.noIssues": "未対応の問題はありません — すべてのドメインがクリーンです。",
    "code.external.noReport": "レポートデータがありません",
    "code.external.noReportDesc": "エグゼクティブレポートを生成するには少なくとも 1 回ドメインスキャンを実行してください。",
    "code.external.noSLAIssues": "未対応の問題なし",
    "code.external.noSLAIssuesDesc": "すべてのドメインがクリーンです。SLA 追跡は不要です。",
    "code.external.noTrends": "データ不足",
    "code.external.noTrendsDesc": "スコアトレンドには 2 回以上のスキャンが必要です。日次監視を有効化してトレンドチャートを埋めてください。",
    "code.external.noVendors": "ベンダーデータがありません",
    "code.external.noVendorsDesc": "ドメインスキャンを実行してサードパーティベンダー (CDN、解析、ホスティング、WAF など) を検出します。",
    "code.external.openIssues": "未対応",
    "code.external.overallRisk": "全体リスク",
    "code.external.overdueBy": "超過",
    "code.external.peerBenchmarkHint": "公開コーパスからの業界ベンチマーク。毎日更新されます。",
    "code.external.peerSectorPrefix": "業界",
    "code.external.perDomainTrend": "ドメイン別スコアトレンド",
    "code.external.postureSub": "監視対象ドメイン全体の外部セキュリティ態勢",
    "code.external.postureTitle": "態勢サマリ",
    "code.external.potentialGain": "潜在的な改善幅",
    "code.external.preset_board": "取締役会",
    "code.external.preset_board_hint": "高レベルの態勢とトレンドのみ。検出結果リストや SLA 詳細は含みません。",
    "code.external.preset_compliance": "コンプライアンス",
    "code.external.preset_compliance_hint": "検出結果 + SLA + コントロール — 外部監査人が必要とする監査証跡。",
    "code.external.preset_custom": "カスタム",
    "code.external.preset_external": "対外",
    "code.external.preset_external_hint": "ベンダー / パートナー / 報道機関向け共有用、サマリビュー + ホスト名のマスキング。",
    "code.external.preset_soc": "SOC",
    "code.external.preset_soc_hint": "マスキングなしの完全版 — 内部運用ブリーフィング向け。",
    "code.external.recentChanges": "直近の変動",
    "code.external.reportAudience": "対象者",
    "code.external.reportSub": "CISO 向け外部セキュリティサマリ",
    "code.external.reportTitle": "エグゼクティブレポート",
    "code.external.risk": "リスク",
    "code.external.riskBreakdown": "リスク内訳",
    "code.external.slaBreaches": "SLA 違反 — 修復期限を超過した問題",
    "code.external.slaBreachesCount": "SLA 違反",
    "code.external.slaSub": "重大度ごとの修復期限遵守状況",
    "code.external.slaTitle": "SLA モニター",
    "code.external.slaViolations": "SLA 違反",
    "code.external.stepByStep": "ステップごと",
    "code.external.supplyAdviceCritical": "重大リスクのベンダーがあります。セキュリティ対策を監査し、外部スクリプトには SRI を設定、最高リスクの依存先には代替も検討してください。",
    "code.external.supplyAdviceOk": "重大リスクのベンダーは検出されていません。ベンダーリスクはインシデントやインフラ更新で変化するため、引き続き監視してください。",
    "code.external.supplyChain": "サプライチェーンインテリジェンス",
    "code.external.supplyChainAdvice": "推奨事項",
    "code.external.supplyChainSub": "監視対象ドメイン全体のサードパーティベンダーリスク",
    "code.external.supplyChainTitle": "サプライチェーンリスク",
    "code.external.topRisk": "最大リスク",
    "code.external.totalVendors": "ベンダー総数",
    "code.external.trendsSub": "セキュリティ態勢と SLA 遵守の履歴",
    "code.external.trendsTitle": "スコアトレンド",
    "code.external.urgentFixes": "緊急の修正",
    "code.external.usedBy": "利用箇所",
    "code.external.vendor": "ベンダー",
    "code.external.vendorBreakdown": "ベンダー内訳",
    "code.external.whatToFixFirst": "最優先で修正する項目",
    "code.external.withinSLA": "SLA 内",

    # item (nav labels)
    "code.item.complianceDashboard": "コンプライアンス",
    "code.item.ctemHistory": "CTEM 履歴",
    "code.item.exposureActions": "アクションプラン",
    "code.item.exposureDNS": "DNS セキュリティ",
    "code.item.exposureEmail": "メールセキュリティ",
    "code.item.exposureHeaders": "Web ヘッダー",
    "code.item.exposureMonitoring": "アラートセンター",
    "code.item.exposurePorts": "ネットワーク公開状況",
    "code.item.exposureReport": "エグゼクティブレポート",
    "code.item.exposureSLA": "SLA モニター",
    "code.item.exposureSSL": "SSL / TLS",
    "code.item.exposureSensitive": "機微ファイル",
    "code.item.exposureSupply": "サプライチェーン",
    "code.item.exposureThreat": "脅威インテリジェンス",
    "code.item.exposureWAF": "WAF と保護",
    "code.item.vaHistory": "VA 履歴",

    # mit (mitigations)
    "code.mit.close": "閉じる",
    "code.mit.evidenceDialogTitle": "証跡履歴",
    "code.mit.evidenceEmpty": "自動チェックの記録はまだありません。毎時走る証跡ワーカーが verification_evidence の URL を検証します — このコントロールに検証可能な URL を設定すると記録が始まります。",

    # monitoring
    "code.monitoring.allSeverities": "全重大度",
    "code.monitoring.allTypes": "全タイプ",
    "code.monitoring.colChange": "変動",
    "code.monitoring.colDescription": "説明",
    "code.monitoring.colDomain": "ドメイン",
    "code.monitoring.colSeverity": "重大度",
    "code.monitoring.colTime": "時刻",
    "code.monitoring.colType": "タイプ",
    "code.monitoring.emptyDesc": "ドメイン全体で変動が検出されると、ここに監視イベントが表示されます。",
    "code.monitoring.emptyTitle": "監視イベントはまだありません",
    "code.monitoring.eventType": "イベントタイプ",
    "code.monitoring.justNow": "たった今",
    "code.monitoring.severity": "重大度",
    "code.monitoring.subtitle": "ドメイン横断のリアルタイム監視イベント",
    "code.monitoring.title": "アラートセンター",

    # paths
    "code.paths.chainProbLabel": "チェーン確率",
    "code.paths.methodGraph": "資産+検出グラフ上の境界付き BFS。確率はエッジごとの重みの積です。",
    "code.paths.methodHeuristic": "手書きのチェーン形状 (v1) とのパターンマッチング。優先度は確率ではなく目立ち度のスコアです。",
    "code.paths.stepsToggle": "エッジ別の内訳",

    # pentest
    "code.pentest.backToProjects": "プロジェクト一覧に戻る",
    "code.pentest.evidence": "証跡",
    "code.pentest.noFindings": "検出結果なし",
    "code.pentest.noFindingsDesc": "スキャンはセキュリティ上の検出結果なしで完了しました。アプリケーションはすべてのチェックに合格しています。",
    "code.pentest.remediation": "修復",
    "code.pentest.scanResults": "スキャン結果",
    "code.pentest.scanResultsSub": "直近のペネトレーションテストの DAST 検出結果",

    # reports
    "code.reports.addSection": "セクションを追加",
    "code.reports.addingTo": "追加先",
    "code.reports.cat.ctem": "CTEM",
    "code.reports.chart.area": "エリアチャート",
    "code.reports.chart.bar": "棒グラフ",
    "code.reports.chart.donut": "ドーナツチャート",
    "code.reports.chart.gauge": "ゲージ",
    "code.reports.chart.heatmap": "ヒートマップ",
    "code.reports.chart.kpi": "KPI カード",
    "code.reports.chart.line": "折れ線グラフ",
    "code.reports.chart.radar": "レーダーチャート",
    "code.reports.chart.radialBar": "ラジアルバー",
    "code.reports.chart.stackedBar": "積み上げ棒グラフ",
    "code.reports.chart.table": "テーブル",
    "code.reports.chart.text": "テキストブロック",
    "code.reports.chart.treemap": "ツリーマップ",
    "code.reports.confirmDeleteTitle": "レポートを削除しますか?",
    "code.reports.deleteSection": "セクションを削除",
    "code.reports.ds.apiDefinitions": "API 定義",
    "code.reports.ds.archMap": "アーキテクチャ",
    "code.reports.ds.attackSurface": "アタックサーフェス",
    "code.reports.ds.autofix": "AutoFix 検出結果",
    "code.reports.ds.autofixRuns": "AutoFix 実行履歴",
    "code.reports.ds.ciChecks": "CI 履歴",
    "code.reports.ds.complianceMatrix": "コンプライアンスマトリクス",
    "code.reports.ds.computedScore": "算出スコア",
    "code.reports.ds.containers": "コンテナ検出結果",
    "code.reports.ds.cspm": "CSPM 検出結果",
    "code.reports.ds.deadCode": "デッドコード",
    "code.reports.ds.dependencies": "依存関係",
    "code.reports.ds.enrichedDeps": "拡張依存関係",
    "code.reports.ds.healthSummary": "健全性サマリ",
    "code.reports.ds.iac": "IaC 検出結果",
    "code.reports.ds.issues": "セキュリティ問題",
    "code.reports.ds.licenses": "ライセンス問題",
    "code.reports.ds.malware": "マルウェアスキャン",
    "code.reports.ds.monitoringEvents": "監視イベント",
    "code.reports.ds.pentestProjects": "ペンテストプロジェクト",
    "code.reports.ds.pulse": "Pulse フィード",
    "code.reports.ds.runtimeEvents": "ランタイムイベント",
    "code.reports.ds.scanDiff": "スキャン差分",
    "code.reports.ds.scanLog": "スキャン履歴",
    "code.reports.ds.scoreEvents": "スコアイベント",
    "code.reports.ds.scoreHistory": "スコア履歴",
    "code.reports.ds.taintFlows": "テイントフロー",
    "code.reports.dsCat.external": "対外",
    "code.reports.moveDown": "下に移動",
    "code.reports.moveUp": "上に移動",
    "code.reports.preset.apiDefsTable": "API ルート",
    "code.reports.preset.archMap": "アーキテクチャマップ",
    "code.reports.preset.assetCount": "資産数",
    "code.reports.preset.assetTypes": "資産タイプ",
    "code.reports.preset.attackSurface": "アタックサーフェス",
    "code.reports.preset.autofixCandidates": "AutoFix 候補",
    "code.reports.preset.autofixCount": "AutoFix 件数",
    "code.reports.preset.autofixRunsTable": "AutoFix 実行履歴",
    "code.reports.preset.autofixSeverity": "AutoFix 重大度別",
    "code.reports.preset.autofixStatus": "AutoFix ステータス別",
    "code.reports.preset.ciHistory": "CI 履歴",
    "code.reports.preset.complianceDetails": "コンプライアンス詳細",
    "code.reports.preset.complianceMatrix": "コンプライアンスマトリクス",
    "code.reports.preset.containerCount": "コンテナ件数",
    "code.reports.preset.containerFindings": "コンテナ検出結果",
    "code.reports.preset.containerSeverity": "コンテナ重大度別",
    "code.reports.preset.cspmFindings": "CSPM 検出結果",
    "code.reports.preset.cspmProvider": "CSPM プロバイダ別",
    "code.reports.preset.cspmSeverity": "CSPM 重大度別",
    "code.reports.preset.deadCodeCount": "デッドコード件数",
    "code.reports.preset.deadCodeTable": "デッドコードテーブル",
    "code.reports.preset.deadCodeType": "デッドコードタイプ別",
    "code.reports.preset.depShared": "最も共有されている依存関係",
    "code.reports.preset.iacFindings": "IaC 検出結果",
    "code.reports.preset.iacFramework": "IaC フレームワーク別",
    "code.reports.preset.iacSeverity": "IaC 重大度別",
    "code.reports.preset.issuesTable": "問題一覧",
    "code.reports.preset.licenseIssues": "ライセンス問題",
    "code.reports.preset.licenseRisk": "ライセンスリスク",
    "code.reports.preset.malwareTable": "マルウェアスキャン",
    "code.reports.preset.monitoringSeverity": "監視重大度別",
    "code.reports.preset.monitoringTable": "監視イベント",
    "code.reports.preset.pentestTable": "ペンテストプロジェクト",
    "code.reports.preset.pentestType": "ペンテストタイプ別",
    "code.reports.preset.projectTypes": "プロジェクトタイプ",
    "code.reports.preset.repoTypes": "リポジトリタイプ",
    "code.reports.preset.runtimeTable": "ランタイムイベント",
    "code.reports.preset.runtimeType": "ランタイムタイプ別",
    "code.reports.preset.scanLogStatus": "スキャンステータス別",
    "code.reports.preset.scanLogTable": "スキャン履歴",
    "code.reports.preset.scoreByCategory": "カテゴリ別スコア",
    "code.reports.preset.scoreEventsTable": "スコア変動",
    "code.reports.preset.scoreTrend": "スコアトレンド",
    "code.reports.preset.secretCount": "シークレット件数",
    "code.reports.preset.taintCategory": "テイントカテゴリ別",
    "code.reports.preset.taintFlows": "テイントフロー",
    "code.reports.preset.taintSeverity": "テイント重大度別",
    "code.reports.preset.textInfo": "情報テキストブロック",
    "code.reports.preset.textWarning": "警告テキストブロック",
    "code.reports.preset.unifiedScore": "統合スコア",
    "code.reports.presets": "プリセット",
    "code.reports.selectOrg": "組織を選択",
    "code.reports.step1": "ステップ 1 — データソース",
    "code.reports.step2": "ステップ 2 — フィールド",
    "code.reports.step3": "ステップ 3 — チャート",
    "code.reports.tmpl.archOverview": "アーキテクチャ概要",
    "code.reports.tmpl.archOverviewDesc": "API ルート、依存関係、デッドコード、テイントフロー分析を含むリポジトリ横断のアーキテクチャマップ。",
    "code.reports.tmpl.autofixReport": "AutoFix 状況レポート",
    "code.reports.tmpl.autofixReportDesc": "自動修復のカバレッジ、パッチ成功率、PR 作成履歴。",
    "code.reports.tmpl.codeQuality": "コード品質レポート",
    "code.reports.tmpl.codeQualityDesc": "デッドコード分析、コード複雑度、テイントフロー経路、修復候補。",
    "code.reports.tmpl.containerSecurity": "コンテナセキュリティレポート",
    "code.reports.tmpl.containerSecurityDesc": "Trivy スキャン結果と修正可用性を含むコンテナイメージの脆弱性分析。",
    "code.reports.tmpl.cspm": "クラウドセキュリティ態勢",
    "code.reports.tmpl.cspmDesc": "AWS、GCP、Azure 全体の CSPM 検出結果と CIS ベンチマーク状況。",
    "code.reports.tmpl.ctemPosture": "CTEM 態勢レポート",
    "code.reports.tmpl.ctemPostureDesc": "ドメイン単位のスコアリング、脅威インテリジェンス、公開状況トレンドを含む外部アタックサーフェス評価。",
    "code.reports.tmpl.externalPosture": "外部態勢レポート",
    "code.reports.tmpl.externalPostureDesc": "外部アタックサーフェス、ペンテストプロジェクト、ドメイン監視イベント、スコアトレンド。",
    "code.reports.tmpl.iacSecurity": "Infrastructure as Code レポート",
    "code.reports.tmpl.iacSecurityDesc": "Terraform、CloudFormation、Kubernetes、Dockerfile における IaC 設定ミス。",
    "code.reports.tmpl.malwareReport": "マルウェア検出レポート",
    "code.reports.tmpl.malwareReportDesc": "依存関係分析からのマルウェアスキャン結果。",
    "code.reports.tmpl.monitoringReport": "監視・アラートレポート",
    "code.reports.tmpl.monitoringReportDesc": "ドメイン監視イベント: 証明書変動、DNS 変動、スコアの後退、新規サブドメイン。",
    "code.reports.tmpl.multiCompliance": "マルチフレームワーク・コンプライアンス",
    "code.reports.tmpl.multiComplianceDesc": "フレームワーク横断のコンプライアンスマトリクス: SOC2、ISO27001、PCI-DSS、OWASP を検出結果に紐付け。",
    "code.reports.tmpl.riskMatrix": "リスクマトリクスレポート",
    "code.reports.tmpl.riskMatrixDesc": "全検出カテゴリの二次元リスク評価: 可能性 vs 影響度。",
    "code.reports.tmpl.runtimeSecurity": "ランタイムセキュリティレポート",
    "code.reports.tmpl.runtimeSecurityDesc": "ランタイムテレメトリイベント: 脅威検出、パストラバーサル、IP ベース攻撃。",
    "code.reports.tmpl.scanActivity": "スキャン履歴レポート",
    "code.reports.tmpl.scanActivityDesc": "ステータス分布、トリガー種別、タイミング分析を含むスキャン実行履歴。",
    "code.reports.tmpl.scoreTrends": "スコアトレンドレポート",
    "code.reports.tmpl.scoreTrendsDesc": "統合スコア履歴、グレード変動、カテゴリ別内訳、スキャン差分分析。",
    "code.reports.tmpl.vaReport": "脆弱性評価 (VA)",
    "code.reports.tmpl.vaReportDesc": "修正可用性、SLA 遵守、証跡チェーンを含む詳細な脆弱性インベントリ。",
    "code.reports.wt.unifiedScore": "統合スコア",

    # scoring / section
    "code.scoring.benchmark": "業界ベンチマーク",
    "code.scoring.benchmarkNoSector": "設定で業界セクターを指定するとピアベンチマークが有効化されます。",
    "code.scoring.sampleSize": "サンプル",
    "code.scoring.topPercentile": "上位パーセンタイル",
    "code.scoring.yourScore": "あなたのスコア",
    "code.section.history": "履歴",

    # warroom duplicates
    "code.warroom.dupActionHint": "このブロックを共有関数またはモジュールに抽出してください。コピーがわずかに分岐している場合は、先に統一してから抽出してください。",
    "code.warroom.dupActionTitle": "修正方法",
    "code.warroom.dupAvgRate": "平均率",
    "code.warroom.dupErrorHint": "ネットワーク接続を確認してページを再読み込みしてください。",
    "code.warroom.dupErrorTitle": "重複データの読み込みに失敗",
    "code.warroom.dupHint": "各行は 2 か所以上に出現するコードブロックです。共有ロジックを関数、モジュール、ユーティリティに抽出すると保守負荷と分岐リスクを減らせます。",
    "code.warroom.dupLocationsTitle": "すべての出現箇所",
    "code.warroom.dupNone": "重複コードは検出されませんでした — クリーンなコードベースです。",
    "code.warroom.dupNoneDesc": "コードベースにコード重複は検出されていません。良好なエンジニアリング習慣の兆候です。",
    "code.warroom.dupTotalBlocks": "ブロック",
    "code.warroom.dupTotalLines": "重複行数",
    "code.warroom.duplicatesSub": "全リポジトリにわたる繰り返しコードブロック",
    "code.warroom.duplicatesTitle": "重複コード",
}


def main():
    """Append the fixed historical Japanese translation dictionary."""
    doc = json.loads(JA.read_text(encoding='utf-8'))
    tr = doc['translations']
    added = 0
    for k, v in T.items():
        if tr.get(k):
            continue
        tr[k] = v
        added += 1
    doc['translations'] = tr
    JA.write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + '\n',
        encoding='utf-8',
    )
    print(f'ja/code.json: added {added} translations (dict size {len(T)})')


if __name__ == '__main__':
    main()
