import json

translations_th = {
  "code.assetMap.accept": "ยอมรับ",
  "code.assetMap.aiSuggest": "AI แนะนำ",
  "code.assetMap.apiAlive": "ออนไลน์",
  "code.assetMap.apiDocs": "เอกสาร API",
  "code.assetMap.apiEndpoints": "จุดเชื่อมต่อ API",
  "code.assetMap.assets": "ทรัพย์สิน",
  "code.assetMap.certs": "ใบรับรอง",
  "code.assetMap.confirm": "ยืนยัน",
  "code.assetMap.confirmed": "ยืนยันแล้ว",
  "code.assetMap.confirmedTitle": "การแมปที่ยืนยันแล้ว",
  "code.assetMap.cveExposureTitle": "การเชื่อมโยง CVE",
  "code.assetMap.dnsSecurity": "ความปลอดภัย DNS",
  "code.assetMap.domains": "โดเมน",
  "code.assetMap.epssHigh": "EPSS > 10%",
  "code.assetMap.expired": "หมดอายุ",
  "code.assetMap.expiring": "ใกล้หมดอายุ (<30 วัน)",
  "code.assetMap.exposedCves": "CVE ที่เปิดเผย",
  "code.assetMap.externalPosture": "ท่าทีภายนอก",
  "code.assetMap.internalCves": "ภายใน",
  "code.assetMap.ips": "IP",
  "code.assetMap.kevCount": "CISA KEV",
  "code.assetMap.mappingCoverage": "ความครอบคลุมการแมป",
  "code.assetMap.mappingDesc": "โดเมนที่เชื่อมโยงกับที่เก็บภายใน",
  "code.assetMap.more": "เพิ่มเติม",
  "code.assetMap.network": "เครือข่าย",
  "code.assetMap.noMappings": "ยังไม่มีการแมป ใช้ AI แนะนำ หรือเชื่อมโยงโดเมนด้วยตนเองด้านล่าง",
  "code.assetMap.openPorts": "พอร์ตที่เปิด",
  "code.assetMap.performance": "ประสิทธิภาพ",
  "code.assetMap.protection": "การป้องกัน",
  "code.assetMap.selectRepo": "เลือก repo...",
  "code.assetMap.sensitiveFiles": "ไฟล์ที่ละเอียดอ่อน",
  "code.assetMap.shodanVulns": "CVE จาก Shodan",
  "code.assetMap.sslIssues": "ปัญหา SSL",
  "code.assetMap.subdomains": "ซับโดเมน",
  "code.assetMap.subtitle": "เชื่อมโยงโดเมนภายนอกกับที่เก็บภายในเพื่อเชื่อมโยง CVE",
  "code.assetMap.suggestionsTitle": "คำแนะนำการแมป",
  "code.assetMap.takeover": "ความเสี่ยงการยึดครอง",
  "code.assetMap.techApi": "เทคโนโลยีและ API",
  "code.assetMap.techDetected": "ตรวจพบเทคโนโลยี",
  "code.assetMap.title": "การแมปทรัพย์สิน",
  "code.assetMap.unmapped": "ยังไม่แมป",
  "code.assetMap.unmappedTitle": "โดเมนที่ยังไม่แมป",
  "code.capability.attackSurface.description": "ค้นพบพื้นผิวการโจมตีภายนอกขององค์กร สแกนโดเมน ซับโดเมน บริการที่เปิดเผย การตั้งค่า SSL บันทึก DNS และสแต็กเทคโนโลยีเพื่อระบุจุดเข้าที่อาจเกิดขึ้น",
  "code.capability.attackSurface.feat1": "การระบุซับโดเมนและวิเคราะห์ DNS",
  "code.capability.attackSurface.feat2": "การตรวจสอบการตั้งค่า SSL/TLS",
  "code.capability.attackSurface.feat3": "การตรวจจับบริการและพอร์ตที่เปิดเผย",
  "code.capability.attackSurface.feat4": "การระบุเทคโนโลยีสแต็ก",
  "code.capability.attackSurface.feat5": "WHOIS และข่าวกรอง IP",
  "code.capability.attackSurface.feat6": "การตรวจสอบ PageSpeed และตัวชี้วัดเว็บ",
  "code.capability.attackSurface.subtitle": "การจัดการพื้นผิวการโจมตี",
  "code.capability.attackSurface.title": "พื้นผิวการโจมตี",
  "code.capability.codeAudit.description": "เชื่อมต่อที่เก็บของคุณและรับการวิเคราะห์ฐานโค้ดอย่างครอบคลุม สแกนหาช่องโหว่ความปลอดภัย โค้ดที่ไม่ใช้งาน จุดซับซ้อน ความเสี่ยงของการพึ่งพา และปัญหาการปฏิบัติตามใบอนุญาต",
  "code.capability.codeAudit.feat1": "การตรวจจับ CVE และความลับในทุกการพึ่งพา",
  "code.capability.codeAudit.feat2": "การระบุโค้ดที่ไม่ใช้งานพร้อมคะแนนความมั่นใจ",
  "code.capability.codeAudit.feat3": "จุดซับซ้อนและการวิเคราะห์ความเสี่ยงจากการเปลี่ยนแปลง",
  "code.capability.codeAudit.feat4": "การเบี่ยงเบนของการพึ่งพาและการปฏิบัติตามใบอนุญาต",
  "code.capability.codeAudit.feat5": "การแมปสถาปัตยกรรมและการค้นพบ API",
  "code.capability.codeAudit.feat6": "คำแนะนำการแก้ไขด้วย AI (AutoFix)",
  "code.capability.codeAudit.subtitle": "การทดสอบความปลอดภัยแอปพลิเคชันแบบคงที่",
  "code.capability.codeAudit.title": "การตรวจสอบโค้ด",
  "code.capability.createProject": "สร้างโปรเจกต์",
  "code.capability.createPrompt": "สร้างโปรเจกต์ใหม่เพื่อเริ่มใช้งานความสามารถนี้",
  "code.capability.features": "สิ่งที่รวมไว้",
  "code.capability.pentest.description": "ทดสอบเว็บไซต์และ API ที่ใช้งานจริงโดยไม่ต้องเข้าถึงซอร์สโค้ด เอนจิน pentest ที่ขับเคลื่อนด้วย AI รันการตรวจสอบ OWASP Top 10 การทดสอบตรรกะธุรกิจ และสร้างรายงานที่มีหลักฐานพร้อมขั้นตอนการสืบพิสูจน์",
  "code.capability.pentest.feat1": "การตรวจสอบอัตโนมัติ OWASP Top 10",
  "code.capability.pentest.feat2": "การตรวจจับ SQL injection, XSS, SSRF",
  "code.capability.pentest.feat3": "การทดสอบการยืนยันตัวตนและเซสชัน",
  "code.capability.pentest.feat4": "การสแกนช่องโหว่ตรรกะธุรกิจ",
  "code.capability.pentest.feat5": "เพลย์บุ๊กการโจมตีที่สร้างโดย AI",
  "code.capability.pentest.feat6": "ภาพหน้าจอหลักฐานและขั้นตอนการสืบพิสูจน์",
  "code.capability.pentest.subtitle": "การทดสอบความปลอดภัยแอปพลิเคชันแบบไดนามิก",
  "code.capability.pentest.title": "การทดสอบเจาะระบบ",
  "code.capability.ready": "พร้อมเริ่มต้นใช้งานหรือยัง?",
  "code.common.count": "จำนวน",
  "code.common.fields": "ฟิลด์",
  "code.common.items": "รายการ",
  "code.common.no": "ไม่",
  "code.common.total": "รวม",
  "code.common.unknown": "ไม่ทราบ",
  "code.common.yes": "ใช่",
  "code.item.assetMap": "แผนที่ทรัพย์สิน",
  "code.item.exposureDomains": "ข่าวกรองโดเมน",
  "code.item.exposurePosture": "ภาพรวมท่าทีความปลอดภัย",
  "code.item.exposureTrends": "แนวโน้มคะแนน",
  "code.nav.attackSurface": "พื้นผิวการโจมตี",
  "code.nav.capabilities": "ความสามารถ",
  "code.nav.codeAudit": "ตรวจสอบโค้ด",
  "code.nav.documentation": "เอกสาร",
  "code.nav.pentestBlackbox": "การทดสอบเจาะระบบ",
  "code.nav.projects": "โปรเจกต์",
  "code.nav.resources": "ทรัพยากร",
  "code.nav.securityNews": "ข่าวความปลอดภัย",
  "code.nav.whatsNew": "มีอะไรใหม่",
  "code.projects.quickStart": "เริ่มต้นด่วน",
  "code.projects.selectType": "ประเภทโปรเจกต์",
  "code.projects.type.attackSurface": "พื้นผิวการโจมตี",
  "code.projects.type.attackSurfaceDesc": "ค้นพบโดเมน ซับโดเมน บริการที่เปิดเผย และปัญหา SSL",
  "code.projects.type.blackbox": "การทดสอบเจาะระบบแบบ Black-box",
  "code.projects.type.blackboxDesc": "ทดสอบเว็บไซต์หรือ API ที่ใช้งานจริงโดยไม่ต้องเข้าถึงซอร์สโค้ด",
  "code.projects.type.codeAudit": "การตรวจสอบโค้ด",
  "code.projects.type.codeAuditDesc": "เชื่อมต่อที่เก็บ สแกนหาช่องโหว่ โค้ดที่ไม่ใช้งาน และการพึ่งพา",
  "code.projects.yourProjects": "โปรเจกต์ของคุณ",
  "code.pulse.actionItems": "รายการดำเนินการ",
  "code.pulse.affected": "ได้รับผลกระทบ",
  "code.reports.addSourceFirst": "เพิ่มแหล่งข้อมูลก่อน",
  "code.reports.addTables": "แหล่งข้อมูล",
  "code.reports.addToReport": "เพิ่มในรายงาน",
  "code.reports.addWidget": "เพิ่มวิดเจ็ต",
  "code.reports.aiGenerated": "สร้างโดย AI",
  "code.reports.aiPolish": "ปรับแต่งด้วย AI",
  "code.reports.aiPolishDone": "ปรับแต่งด้วย AI แล้ว",
  "code.reports.aiPolishError": "การปรับแต่งด้วย AI ล้มเหลว",
  "code.reports.aiPolishing": "กำลังปรับแต่งด้วย AI...",
  "code.reports.autofixReady": "AutoFix พร้อมใช้งาน",
  "code.reports.avgLabel": "เฉลี่ย",
  "code.reports.cat.advanced": "ขั้นสูง",
  "code.reports.cat.compliance": "การปฏิบัติตาม",
  "code.reports.cat.opensource": "โอเพนซอร์ส",
  "code.reports.cat.security": "ความปลอดภัย",
  "code.reports.catalog": "รายงาน",
  "code.reports.chartPreview": "แผนภูมิ + ข้อมูล",
  "code.reports.clearAiPolish": "ล้าง AI",
  "code.reports.clickToAdd": "คลิกวิดเจ็ตเพื่อเพิ่มในรายงาน",
  "code.reports.col.asset_type": "ประเภท",
  "code.reports.col.autofix_eligible": "AutoFix",
  "code.reports.col.blast": "Blast",
  "code.reports.col.blast_radius": "Blast Radius",
  "code.reports.col.branch": "สาขา",
  "code.reports.col.category": "หมวดหมู่",
  "code.reports.col.check_name": "การตรวจสอบ",
  "code.reports.col.commit": "Commit",
  "code.reports.col.commit_sha": "Commit",
  "code.reports.col.complex_fns_delta": "การเปลี่ยนแปลงความซับซ้อน",
  "code.reports.col.complex_functions": "ฟังก์ชันซับซ้อน",
  "code.reports.col.created_at": "สร้างเมื่อ",
  "code.reports.col.critical_count": "วิกฤติ",
  "code.reports.col.cve_critical": "CVE วิกฤติ",
  "code.reports.col.cve_high": "CVE สูง",
  "code.reports.col.cve_id": "CVE ID",
  "code.reports.col.cve_total": "CVE รวม",
  "code.reports.col.date": "วันที่",
  "code.reports.col.dead_code_count": "โค้ดที่ไม่ใช้งาน",
  "code.reports.col.dead_code_delta": "การเปลี่ยนแปลงโค้ดที่ไม่ใช้งาน",
  "code.reports.col.description": "คำอธิบาย",
  "code.reports.col.detected_at": "ตรวจพบเมื่อ",
  "code.reports.col.discovered_at": "ค้นพบเมื่อ",
  "code.reports.col.file": "ไฟล์",
  "code.reports.col.file_path": "ไฟล์",
  "code.reports.col.fixed_version": "เวอร์ชันที่แก้ไข",
  "code.reports.col.framework": "เฟรมเวิร์ก",
  "code.reports.col.generated_at": "สร้างเมื่อ",
  "code.reports.col.guideline": "แนวทาง",
  "code.reports.col.health_grade": "เกรด",
  "code.reports.col.health_score": "คะแนนสุขภาพ",
  "code.reports.col.high_count": "สูง",
  "code.reports.col.image_ref": "ภาพ",
  "code.reports.col.license_name": "ใบอนุญาต",
  "code.reports.col.line": "บรรทัด",
  "code.reports.col.name": "ชื่อ",
  "code.reports.col.new_cves_count": "CVE ใหม่",
  "code.reports.col.package": "แพ็กเกจ",
  "code.reports.col.package_name": "แพ็กเกจ",
  "code.reports.col.patch_status": "สถานะแพทช์",
  "code.reports.col.path": "ไฟล์",
  "code.reports.col.pr_url": "URL ของ PR",
  "code.reports.col.project_type": "ประเภทโปรเจกต์",
  "code.reports.col.published_at": "เผยแพร่เมื่อ",
  "code.reports.col.reason": "เหตุผล",
  "code.reports.col.repo": "Repo",
  "code.reports.col.repo_id": "Repo ID",
  "code.reports.col.repo_name": "Repo",
  "code.reports.col.repos_compared": "ที่เก็บที่เปรียบเทียบ",
  "code.reports.col.resolved_cves_count": "CVE ที่แก้ไขแล้ว",
  "code.reports.col.resource_type": "ทรัพยากร",
  "code.reports.col.risk_level": "ระดับความเสี่ยง",
  "code.reports.col.rule_category": "หมวดหมู่",
  "code.reports.col.scanned_at": "สแกนล่าสุด",
  "code.reports.col.secret_count": "ความลับ",
  "code.reports.col.secrets_delta": "การเปลี่ยนแปลงความลับ",
  "code.reports.col.security_findings": "ผลการค้นหาความปลอดภัย",
  "code.reports.col.severity": "ความรุนแรง",
  "code.reports.col.shared_count": "ใช้ร่วมโดย",
  "code.reports.col.sink": "ปลายทาง",
  "code.reports.col.sink_file": "ไฟล์ปลายทาง",
  "code.reports.col.source": "แหล่งที่มา",
  "code.reports.col.source_file": "ไฟล์ต้นทาง",
  "code.reports.col.status": "สถานะ",
  "code.reports.col.summary": "สรุป",
  "code.reports.col.taint_flows_delta": "การเปลี่ยนแปลง Taint",
  "code.reports.col.title": "ชื่อเรื่อง",
  "code.reports.col.total_count": "รวม",
  "code.reports.col.total_uses": "การใช้งานทั้งหมด",
  "code.reports.col.type": "ประเภท",
  "code.reports.col.value": "ค่า",
  "code.reports.col.verify_passed": "ยืนยันแล้ว",
  "code.reports.componentName": "ชื่อ...",
  "code.reports.confirmDelete": "ลบรายงานนี้? ไม่สามารถย้อนกลับได้",
  "code.reports.countOption": "จำนวน",
  "code.reports.currentWidgets": "วิดเจ็ตในรายงาน",
  "code.reports.dataDesigner": "ออกแบบข้อมูล",
  "code.reports.dataPreview": "ตัวอย่างข้อมูล",
  "code.reports.deletedSuccess": "ลบแล้ว",
  "code.reports.dragToJoin": "ลากจากพอร์ตไปพอร์ตเพื่อสร้าง JOIN",
  "code.reports.drawEdge": "ลากเพื่อสร้าง JOIN",
  "code.reports.dsCat.architecture": "สถาปัตยกรรม",
  "code.reports.dsCat.ci": "CI/CD",
  "code.reports.dsCat.compliance": "การปฏิบัติตาม",
  "code.reports.dsCat.health": "สุขภาพ",
  "code.reports.dsCat.security": "ความปลอดภัย",
  "code.reports.emptyLayout": "เพิ่มองค์ประกอบจากด้านล่าง",
  "code.reports.emptyReportError": "เพิ่มวิดเจ็ตอย่างน้อยหนึ่งรายการก่อนบันทึก",
  "code.reports.emptySection": "คลิกวิดเจ็ตทางขวาเพื่อเพิ่มที่นี่",
  "code.reports.executiveSummary": "สรุปผู้บริหาร",
  "code.reports.exportPdf": "PDF",
  "code.reports.failedToLoadData": "ไม่สามารถโหลดข้อมูลได้",
  "code.reports.fieldLabel": "ป้ายกำกับ",
  "code.reports.fieldValue": "ค่า",
  "code.reports.generated": "สร้างแล้ว",
  "code.reports.generating": "กำลังสร้าง PDF...",
  "code.reports.generatingPro": "กำลังสร้าง...",
  "code.reports.joinResult": "ข้อมูล",
  "code.reports.labelField": "หมวดหมู่ / ป้ายกำกับ",
  "code.reports.layout": "เค้าโครง",
  "code.reports.myComponents": "องค์ประกอบของฉัน",
  "code.reports.myReports": "รายงานของฉัน",
  "code.reports.nameRequired": "ต้องระบุชื่อรายงาน",
  "code.reports.newCustom": "รายงานกำหนดเองใหม่",
  "code.reports.noComponents": "ออกแบบวิดเจ็ตด้านบนและบันทึกที่นี่",
  "code.reports.noData": "ไม่มีข้อมูล",
  "code.reports.noDataAvailable": "ไม่มีข้อมูล",
  "code.reports.noFindings": "ไม่พบผลลัพธ์",
  "code.reports.noWidgetsToPolish": "ไม่มีวิดเจ็ตที่จะปรับแต่ง",
  "code.reports.noWidgetsYet": "ยังไม่มีวิดเจ็ต",
  "code.reports.noneCountOption": "ไม่มี (จำนวน)",
  "code.reports.noneOption": "ไม่มี",
  "code.reports.openDesigner": "เปิดออกแบบข้อมูล (JOIN)",
  "code.reports.pickSource": "เลือกแหล่งข้อมูล...",
  "code.reports.preset.ciPassFail": "CI ผ่าน/ไม่ผ่าน",
  "code.reports.preset.cveCount": "จำนวน CVE",
  "code.reports.preset.depTreemap": "แผนผังการพึ่งพา",
  "code.reports.preset.findingsTable": "ตารางผลลัพธ์",
  "code.reports.preset.gradeDistribution": "การกระจายเกรด",
  "code.reports.preset.healthGauge": "มาตรวัดสุขภาพ",
  "code.reports.preset.issueTypes": "ประเภทปัญหา",
  "code.reports.preset.licenseDistribution": "การกระจายใบอนุญาต",
  "code.reports.preset.severityBar": "แผนภูมิแท่งความรุนแรง",
  "code.reports.preset.severityDonut": "แผนภูมิวงกลมความรุนแรง",
  "code.reports.preview": "ตัวอย่าง",
  "code.reports.previewTimeout": "รายงานใช้เวลานานเกินไปในการโหลด ลองอีกครั้ง",
  "code.reports.print": "พิมพ์",
  "code.reports.proPdf": "Pro PDF",
  "code.reports.proReportError": "การสร้างรายงาน Pro ล้มเหลว",
  "code.reports.proReportGenerated": "สร้างรายงาน Pro แล้ว",
  "code.reports.recommendations": "คำแนะนำ",
  "code.reports.reportDeleted": "ลบรายงานแล้ว",
  "code.reports.reportLayout": "เค้าโครงรายงาน",
  "code.reports.reportSaved": "บันทึกรายงานแล้ว",
  "code.reports.save": "บันทึก",
  "code.reports.saveError": "การบันทึกล้มเหลว",
  "code.reports.saveToLibrary": "บันทึกในคลัง",
  "code.reports.savedSuccess": "บันทึกในคลังแล้ว",
  "code.reports.searchReports": "ค้นหารายงาน...",
  "code.reports.searchWidgets": "ค้นหาวิดเจ็ต...",
  "code.reports.selectChart": "แผนภูมิ",
  "code.reports.selectFields": "ฟิลด์",
  "code.reports.selectSource": "แหล่งข้อมูล",
  "code.reports.showingRows": "แสดง 100 จาก {n} แถว",
  "code.reports.tmpl.ciHistory": "ประวัติการสแกน CI",
  "code.reports.tmpl.ciHistoryDesc": "ภาพรวมการสแกน PR ที่ผ่านและไม่ผ่านทั้งหมด",
  "code.reports.tmpl.cveDatabase": "ฐานข้อมูล CVE",
  "code.reports.tmpl.cveDatabaseDesc": "ค้นหา CVE ทั้งหมดที่ตรวจสอบพร้อมที่เก็บที่ได้รับผลกระทบและไทม์ไลน์",
  "code.reports.tmpl.iso27001": "ISO 27001:2022",
  "code.reports.tmpl.iso27001Desc": "สถานะการปฏิบัติตามมาตรฐาน ISO 27001",
  "code.reports.tmpl.licenseSbom": "ใบอนุญาตและ SBOM",
  "code.reports.tmpl.licenseSbomDesc": "การวิเคราะห์ความเสี่ยงใบอนุญาตโอเพนซอร์สและบัญชีรายการซอฟต์แวร์",
  "code.reports.tmpl.owasp": "OWASP Top 10",
  "code.reports.tmpl.owaspDesc": "แมปผลลัพธ์กับหมวดหมู่ OWASP Top 10",
  "code.reports.tmpl.pentestReport": "รายงาน Pentest",
  "code.reports.tmpl.pentestReportDesc": "ผลลัพธ์แคมเปญ Red Team และข้อมูลเชิงลึก SLA",
  "code.reports.tmpl.securityAudit": "รายงานการตรวจสอบความปลอดภัย",
  "code.reports.tmpl.securityAuditDesc": "ภาพรวมท่าทีความปลอดภัยอย่างครอบคลุมพร้อมผลลัพธ์ การกระจายความรุนแรง และแผนการแก้ไข",
  "code.reports.tmpl.soc2": "SOC 2",
  "code.reports.tmpl.soc2Desc": "ความครอบคลุมการปฏิบัติตาม SOC 2 Type II",
  "code.reports.tmpl.trend": "แนวโน้มตามเวลา",
  "code.reports.tmpl.trendDesc": "ดูวิวัฒนาการของปัญหาที่เปิดอยู่ตามเวลา",
  "code.reports.totalCves": "CVE รวม",
  "code.reports.totalRecords": "รายการทั้งหมด",
  "code.reports.unknownSource": "แหล่งที่มาไม่ทราบ",
  "code.reports.untitled": "รายงานไม่มีชื่อ",
  "code.reports.valueField": "ค่า / ตัวชี้วัด",
  "code.reports.widget.autofix-count": "AutoFix พร้อมใช้งาน",
  "code.reports.widget.ci-history": "ประวัติการสแกน CI",
  "code.reports.widget.executive-summary": "สรุปผู้บริหาร (AI)",
  "code.reports.widget.finding-table": "ตารางผลลัพธ์",
  "code.reports.widget.grade-donut": "การกระจายเกรด",
  "code.reports.widget.health-dots": "ภาพรวมสุขภาพ",
  "code.reports.widget.health-gauge": "คะแนนสุขภาพ",
  "code.reports.widget.issue-count": "สรุปปัญหา",
  "code.reports.widget.license-table": "สรุปใบอนุญาต",
  "code.reports.widget.severity-bar": "การกระจายความรุนแรง",
  "code.reports.widget.text-block": "ข้อความกำหนดเอง",
  "code.reports.widget.trend-chart": "แนวโน้มตามเวลา",
  "code.reports.wt.aiSummary": "สรุปผู้บริหาร AI",
  "code.reports.wt.allCves": "CVE ทั้งหมด",
  "code.reports.wt.allFindings": "ผลลัพธ์ทั้งหมด",
  "code.reports.wt.assetStatus": "สถานะทรัพย์สิน",
  "code.reports.wt.assetTypes": "ประเภทของทรัพย์สิน",
  "code.reports.wt.autofixCandidates": "ผู้สมัคร AutoFix",
  "code.reports.wt.blastBySeverity": "Blast จำแนกตามความรุนแรง",
  "code.reports.wt.checkHistory": "ประวัติการตรวจสอบ",
  "code.reports.wt.ciByBranch": "ผลลัพธ์ตามสาขา",
  "code.reports.wt.ciPassFail": "CI ผ่าน/ไม่ผ่าน",
  "code.reports.wt.containerImages": "ภาพคอนเทนเนอร์",
  "code.reports.wt.containerVulns": "ช่องโหว่คอนเทนเนอร์",
  "code.reports.wt.cveByRepo": "CVE ตาม Repo",
  "code.reports.wt.cveSeverity": "ความรุนแรง CVE",
  "code.reports.wt.depBlastRadius": "Blast Radius การพึ่งพา",
  "code.reports.wt.depUsage": "การใช้งานการพึ่งพา",
  "code.reports.wt.discoveredAssets": "ทรัพย์สินที่ค้นพบ",
  "code.reports.wt.findingTypes": "ประเภทผลลัพธ์",
  "code.reports.wt.gradeDistribution": "การกระจายเกรด",
  "code.reports.wt.healthByRepo": "สุขภาพตาม Repo",
  "code.reports.wt.healthScore": "คะแนนสุขภาพ",
  "code.reports.wt.iacBySeverity": "IaC จำแนกตามความรุนแรง",
  "code.reports.wt.iacFindings": "ผลลัพธ์ IaC",
  "code.reports.wt.iacFrameworks": "เฟรมเวิร์ก IaC",
  "code.reports.wt.issueTypes": "ประเภทปัญหา",
  "code.reports.wt.licenseDistribution": "การกระจายใบอนุญาต",
  "code.reports.wt.licenseIssues": "ปัญหาใบอนุญาต",
  "code.reports.wt.orgHealth": "สุขภาพองค์กร",
  "code.reports.wt.pulseItems": "รายการ Pulse",
  "code.reports.wt.riskLevels": "ระดับความเสี่ยง",
  "code.reports.wt.scanDelta": "การเปลี่ยนแปลงจากการสแกน",
  "code.reports.wt.severityDistribution": "การกระจายความรุนแรง",
  "code.reports.wt.severitySplit": "การแบ่งความรุนแรง",
  "code.reports.wt.sharedPackages": "แพ็กเกจที่ใช้ร่วมกัน",
  "code.reports.wt.socAutofixStatus": "สถานะ AutoFix",
  "code.reports.wt.socCiGate": "ผลลัพธ์ CI Gate",
  "code.reports.wt.socIssueSeverity": "ความรุนแรงของปัญหา",
  "code.reports.wt.taintCategories": "หมวดหมู่ Taint",
  "code.reports.wt.topFindings": "ผลลัพธ์ชั้นนำตาม Blast Radius",
  "code.reports.wt.totalCves": "CVE รวม",
  "code.scoring.advisoryOnly": "ที่ปรึกษา — ไม่ส่งผลต่อการจัดอันดับ",
  "code.scoring.cat.attackSurface": "พื้นผิวการโจมตี",
  "code.scoring.cat.codeSecurity": "ความปลอดภัยโค้ด",
  "code.scoring.complexity": "ความซับซ้อน",
  "code.scoring.deadCode": "โค้ดที่ไม่ใช้งาน",
  "code.scoring.documentation": "เอกสาร",
  "code.scoring.howCalculated": "คำนวณอย่างไร?",
  "code.scoring.methodDesc": "คะแนนรวมเป็นค่าเฉลี่ยถ่วงน้ำหนักของมิติที่ใช้งานอยู่ มิติที่ไม่มีข้อมูลการสแกนจะถูกยกเว้นโดยอัตโนมัติ และน้ำหนักจะถูกแจกจ่ายใหม่ให้กับมิติที่เหลือ",
  "code.scoring.mode.context": "บริบท — เป็นข้อมูลเท่านั้น ไม่นำมาคิดคะแนน",
  "code.scoring.mode.contextLabel": "บริบท — เป็นข้อมูลเท่านั้น",
  "code.scoring.mode.observing": "กำลังสังเกต — เก็บข้อมูลแต่ยังไม่คิดคะแนน",
  "code.scoring.mode.observingLabel": "กำลังสังเกต — เก็บข้อมูลแต่ยังไม่คิดคะแนน",
  "code.scoring.overall": "ภาพรวม",
  "code.scoring.security": "ความปลอดภัย",
  "code.scoring.sv.apiSecurity": "ความปลอดภัย API",
  "code.scoring.sv.breachExposure": "การรั่วไหลข้อมูล",
  "code.scoring.sv.dnsSecurity": "ความปลอดภัย DNS",
  "code.scoring.sv.duplicateCode": "โค้ดซ้ำ",
  "code.scoring.sv.emailSecurity": "ความปลอดภัยอีเมล",
  "code.scoring.sv.ipIntel": "ข่าวกรอง IP",
  "code.scoring.sv.jsBundle": "JS Bundles",
  "code.scoring.sv.licenseCompliance": "การปฏิบัติตามใบอนุญาต",
  "code.scoring.sv.malwarePackages": "มัลแวร์",
  "code.scoring.sv.openPorts": "พอร์ตที่เปิด",
  "code.scoring.sv.pagespeed": "PageSpeed",
  "code.scoring.sv.sensitiveFiles": "ไฟล์ที่ละเอียดอ่อน",
  "code.scoring.sv.sslTls": "TLS / SSL",
  "code.scoring.sv.supplyChainRisk": "ความเสี่ยงห่วงโซ่อุปทาน",
  "code.scoring.sv.taintFlows": "การไหลของ Taint",
  "code.scoring.sv.techStack": "Tech Stack",
  "code.scoring.sv.threatIntel": "ข่าวกรองภัยคุกคาม",
  "code.scoring.sv.triageEffort": "ความพยายามในการคัดกรอง",
  "code.scoring.sv.wafProtection": "การป้องกัน WAF",
  "code.scoring.sv.webHeaders": "ส่วนหัวเว็บ",
  "code.scoring.sv.whois": "WHOIS",
  "code.scoring.viewDetails": "ดูรายละเอียด",
  "code.section.exposure": "ข่าวกรองการเปิดเผย",
  "code.settings.scanLog.complete": "เสร็จสิ้น",
  "code.settings.scanLog.empty": "ยังไม่มีประวัติการสแกน",
  "code.settings.scanLog.failed": "ล้มเหลว",
  "code.settings.scanLog.total": "รวม",
  "code.settings.tab.scanLog": "บันทึกการสแกน",
  "code.severity.critical": "วิกฤติ",
  "code.severity.high": "สูง",
  "code.severity.low": "ต่ำ",
  "code.severity.medium": "ปานกลาง",
  "code.severity.moderate": "ปานกลาง",
  "code.studio.aiProposals": "ข้อเสนอ AI",
  "code.studio.autofixReady": "AutoFix พร้อมใช้งาน",
  "code.studio.briefing": "สรุปสถานการณ์",
  "code.studio.copyAiPrompt": "คัดลอก AI Fix Prompt",
  "code.studio.hotFindings": "ผลลัพธ์ที่สำคัญ",
  "code.studio.noActions": "ไม่มีการดำเนินการด่วน",
  "code.studio.noFindings": "ไม่พบผลลัพธ์วิกฤติ",
  "code.studio.noFixPlan": "ไม่มีแผนแก้ไข — รันการสแกนก่อน",
  "code.studio.noRecommendations": "ยังไม่มีคำแนะนำจาก AI",
  "code.studio.quickActions": "การดำเนินการด่วน",
  "code.studio.selectOrg": "เลือกองค์กรเพื่อเริ่มต้น",
  "code.studio.totalEffort": "{n} ชั่วโมง",
  "code.studio.week1": "สัปดาห์ที่ 1",
}

filepath = "C:/Users/aa090/\u5c08\u6848/flytohub/flyto-i18n/locales/code/th/code.json"

with open(filepath, encoding="utf-8") as f:
    data = json.load(f)

tr = data["translations"]
updated = 0
not_found = []
for k, v in translations_th.items():
    if k in tr and tr[k] == "":
        tr[k] = v
        updated += 1
    elif k not in tr:
        not_found.append(k)

print(f"Updated {updated} keys")
if not_found:
    print(f"Not found: {not_found}")

remaining = [k for k, v in tr.items() if v == ""]
print(f"Remaining empty: {len(remaining)}")
if remaining:
    print(remaining)

with open(filepath, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Done writing file.")
