#!/usr/bin/env python3
"""Generate and verify the source-linked Python declaration reference."""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "generated" / "python-symbols.md"


@dataclass(frozen=True)
class Declaration:
    """Describe one documented Python class, function, or method."""

    kind: str
    symbol: str
    source: str
    line: int
    summary: str


def source_files() -> list[Path]:
    """Return every maintained, historical, and test Python source file."""
    files = [path for path in (ROOT / "scripts").rglob("*.py") if "__pycache__" not in path.parts]
    files.extend((ROOT / "tests").glob("*.py"))
    legacy = ROOT / "translate_th.py"
    if legacy.exists():
        files.append(legacy)
    return sorted(set(files))


def declaration_kind(node: ast.AST, parent_kind: str | None) -> str:
    """Classify an AST declaration for the generated table."""
    if isinstance(node, ast.ClassDef):
        return "class"
    if parent_kind == "class":
        return "method"
    if isinstance(node, ast.AsyncFunctionDef):
        return "async function"
    return "function"


def first_sentence(docstring: str) -> str:
    """Collapse a docstring into a Markdown-table-safe summary."""
    compact = " ".join(docstring.split())
    sentence_end = compact.find(". ")
    if sentence_end >= 0:
        compact = compact[: sentence_end + 1]
    return compact.replace("|", "\\|")


def walk_declarations(
    nodes: list[ast.stmt],
    path: Path,
    parents: tuple[str, ...] = (),
    parent_kind: str | None = None,
) -> list[Declaration]:
    """Recursively collect declarations while preserving qualified names."""
    declarations: list[Declaration] = []
    for node in nodes:
        if not isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        docstring = ast.get_docstring(node, clean=True)
        symbol = ".".join((*parents, node.name))
        if not docstring:
            raise ValueError(f"{path.relative_to(ROOT)}:{node.lineno} {symbol} has no docstring")
        kind = declaration_kind(node, parent_kind)
        declarations.append(
            Declaration(
                kind=kind,
                symbol=symbol,
                source=path.relative_to(ROOT).as_posix(),
                line=node.lineno,
                summary=first_sentence(docstring),
            )
        )
        declarations.extend(
            walk_declarations(
                node.body,
                path,
                (*parents, node.name),
                "class" if isinstance(node, ast.ClassDef) else "function",
            )
        )
    return declarations


def collect_declarations() -> list[Declaration]:
    """Parse every source file and return sorted documented declarations."""
    declarations: list[Declaration] = []
    for path in source_files():
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        declarations.extend(walk_declarations(tree.body, path))
    return sorted(declarations, key=lambda item: (item.source, item.line, item.symbol))


def render_reference(declarations: list[Declaration]) -> str:
    """Render a deterministic Markdown table for all Python declarations."""
    lines = [
        "# Generated Python Symbol Reference",
        "",
        "Generated by `python3 scripts/generate-reference.py --write`. Do not edit",
        "this file by hand. Every class, function, nested function, test, and method",
        "under `scripts/` and `tests/` must have a source docstring.",
        "",
        f"Declarations: **{len(declarations)}**",
        "",
        "| Kind | Symbol | Source | Contract summary |",
        "| --- | --- | --- | --- |",
    ]
    for item in declarations:
        lines.append(
            f"| {item.kind} | `{item.symbol}` | "
            f"[`{item.source}:{item.line}`](../../{item.source}#L{item.line}) | {item.summary} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    """Write the reference or fail when the tracked output is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="replace the tracked reference")
    args = parser.parse_args()

    try:
        rendered = render_reference(collect_declarations())
    except (OSError, SyntaxError, ValueError) as exc:
        print(f"generate-reference: {exc}", file=sys.stderr)
        return 1

    if args.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(ROOT)}")
        return 0

    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
        print("generated Python reference is stale; run with --write", file=sys.stderr)
        return 1
    print(f"Python reference is current ({len(collect_declarations())} declarations)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
